/*
 * JBoss, Home of Professional Open Source
 * Copyright 2010, Red Hat, Inc. and/or its affiliates,
 * and individual contributors as indicated by the @author tags.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2010,
 * @author JBoss, by Red Hat.
 */
package org.aries.tx.recovery.logger;

import static org.jboss.logging.Logger.Level.WARN;

import java.text.MessageFormat;

import org.jboss.logging.Logger;

/**
 * i18n log messages for the wst module.
 * This class is autogenerated. Don't mess with it.
 *
 * @author Jonathan Halliday (jonathan.halliday@redhat.com) 2010-06
 */
public class wstI18NLoggerImpl implements wstI18NLogger {

	private final Logger logger;

	wstI18NLoggerImpl(Logger logger) {
		this.logger = logger;
	}

	public String get_recovery_participant_at_ATParticipantRecoveryRecord_restoreParticipant_1(String arg0) {
		return MessageFormat.format("ARJUNA-43216 participant {0} has no saved recovery state to recover", arg0);
	}

	public void warn_recovery_participant_at_ATParticipantRecoveryRecord_restoreState_1(String arg0, Throwable arg1) {
		logger.logv(WARN, arg1, "ARJUNA-43217 XML stream exception restoring recovery state for participant {0}", arg0);
	}

	public void warn_recovery_participant_at_ATParticipantRecoveryRecord_restoreState_2(String arg0, Throwable arg1) {
		logger.logv(WARN, arg1, "ARJUNA-43218 I/O exception saving restoring state for participant {0}", arg0);
	}

	public void warn_recovery_participant_at_ATParticipantRecoveryRecord_saveState_1(String arg0) {
		logger.logv(WARN, "ARJUNA-43219 Could not save recovery state for non-serializable durable WS-AT participant {0}", arg0);
	}

	public void warn_recovery_participant_at_ATParticipantRecoveryRecord_saveState_2(String arg0, Throwable arg1) {
		logger.logv(WARN, arg1, "ARJUNA-43220 XML stream exception saving recovery state for participant {0}", arg0);
	}

	public void warn_recovery_participant_at_ATParticipantRecoveryRecord_saveState_3(String arg0, Throwable arg1) {
		logger.logv(WARN, arg1, "ARJUNA-43221 I/O exception saving recovery state for participant {0}", arg0);
	}

	public String get_recovery_participant_ba_BAParticipantRecoveryRecord_restoreParticipant_1(String arg0) {
		return MessageFormat.format("ARJUNA-43222 participant {0} has no saved recovery state to recover", arg0);
	}

	public void warn_recovery_participant_ba_BAParticipantRecoveryRecord_restoreState_1(String arg0, Throwable arg1) {
		logger.logv(WARN, arg1, "ARJUNA-43223 XML stream exception restoring recovery state for participant {0}", arg0);
	}

	public void warn_recovery_participant_ba_BAParticipantRecoveryRecord_restoreState_2(String arg0, Throwable arg1) {
		logger.logv(WARN, arg1, "ARJUNA-43224 I/O exception saving restoring state for participant {0}", arg0);
	}

	public void warn_recovery_participant_ba_BAParticipantRecoveryRecord_saveState_1(String arg0) {
		logger.logv(WARN, "ARJUNA-43225 Could not save recovery state for non-serializable WS-BA participant {0}", arg0);
	}

	public void warn_recovery_participant_ba_BAParticipantRecoveryRecord_saveState_2(String arg0, Throwable arg1) {
		logger.logv(WARN, arg1, "ARJUNA-43226 XML stream exception saving recovery state for participant {0}", arg0);
	}

	public void warn_recovery_participant_ba_BAParticipantRecoveryRecord_saveState_3(String arg0, Throwable arg1) {
		logger.logv(WARN, arg1, "ARJUNA-43227 I/O exception saving recovery state for participant {0}", arg0);
	}
}
