package org.aries.launcher;

import org.aries.launcher.MavenExecutionHarness;
import org.aries.launcher.MavenProgram;
import org.aries.util.test.AbstractMultiThreadedIT;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.runners.MockitoJUnitRunner;


/**
 * Generated by Nam.
 *
 */
@RunWith(MockitoJUnitRunner.class)
public class MavenExecutionHarnessIT extends AbstractMultiThreadedIT {

	private MavenExecutionHarness fixture;

	private static boolean executeComplete;


	@Before
	public void setUp() throws Exception {
		super.setUp();
		fixture = createFixture();
		executeComplete = false;
	}

	@After
	public void tearDown() throws Exception {
		fixture.shutdown();
		fixture = null;
		super.tearDown();
	}

	protected MavenExecutionHarness createFixture() throws Exception {
		MavenProgram program = createProgramForTest();
		//ObjectUtil.writeObjectToTempFile(program, program.getName());
		fixture = new MavenExecutionHarness(program);
		return fixture;
	}

	protected MavenProgram createProgramForTest() {
		MavenProgram program = new MavenProgram();
		program.setName("maven_execution_harness_test");
		program.setMavenHome("c:/software/apache-maven-3.0.4");
		program.setMainClass(MavenExecutionHarness.class.getName());
		program.getGoals().add("validate");
		program.setHostName("localhost");
		program.setJmxPort(1199);
		program.initialize();
		return program;
	}

	@Test
	public void testExecute() throws Exception {
		fixture.initialize();
		fixture.execute();
	}

}
