<?xml version="1.0" encoding="UTF-8"?>

<definitions
	name="TestAssignCollections"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
	xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:testing="http://testing"
	targetNamespace="http://testing">

	<import location="TestAssignCollections.xsd" namespace="http://testing"/>

	<message name="IntegerArrayMessage">
		<part name="IntegerArray" type="testing:ArrayOfInteger" />
	</message>

	<message name="StringArrayMessage">
		<part name="StringArray" type="testing:ArrayOfString" />
	</message>
	
	<portType name="Receiver">
		<operation name="receive">
			<input message="testing:IntegerArrayMessage" name="IntegerArrayMessage" />
			<!-- Oneway operation: No output or fault elements here -->
		</operation>
	</portType>

	<service name="ReceiverService">
		<port binding="testing:ReceiverHTTPBinding" name="Receiver">
			<soap:address location="http://localhost:8080/ReceiverService/Receiver" />
		</port>
	</service>

	<plnk:partnerLinkType name="test-link-type">
		<plnk:role name="tester" portType="testing:Receiver"/>
	</plnk:partnerLinkType>

	<binding name="ReceiverHTTPBinding" type="testing:Receiver">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="receive">
			<soap:operation soapAction="" />
			<input name="IntegerArrayMessage">
				<soap:body namespace="http://testing" use="literal" />
			</input>
		</operation>
	</binding>
</definitions>
