package simpleinvoke.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

/**
 * Generated by Nam.
 *
 */
@WebService(name = "SimpleInvoke", serviceName = "SimpleInvokeService", portName = "SimpleInvokePort", targetNamespace = "http://www.jboss.org/bpel/examples/wsdl")
public class SimpleInvokeImpl implements SimpleInvoke {

	@WebMethod
	@WebResult(name = "response")
	public String sayHelloTo(@WebParam(name = "request") String toWhom) {
		HelloWorldWSProxy client = new HelloWorldWSProxy();
		SayHello sayHello = new SayHello();
		sayHello.setToWhom(toWhom);
		SayHelloResponse sayHelloResponse = client.sayHello(sayHello);
		String response = sayHelloResponse.getReply();
		return response;
	}

}
