SET FOREIGN_KEY_CHECKS = 0;
set autocommit = 0;
delete from `permission`;
delete from `preferences`;
delete from `registration`;
delete from `role`;
delete from `skin`;
delete from `user`;
delete from `attachment`;
delete from `email_account`;
delete from `email_address`;
delete from `email_address_list`;
delete from `email_box`;
delete from `email_message`;
delete from `person`;
delete from `person_name`;
delete from `phone_number`;
delete from `property`;
delete from `street_address`;
delete from `zip_code`;
commit;
