package org.aries.bank;

import java.io.Serializable;
import java.lang.Long;
import java.lang.String;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankLoanQuoteRequest", propOrder = {
	"id",
	"borrowerName",
	"borrowerSsn",
	"creditHistory",
	"creditScore",
	"loanAmount",
	"loanDuration"
})
@XmlRootElement(name = "bankLoanQuoteRequest")
public class BankLoanQuoteRequest implements Serializable {

	public static final long serialVersionUID = 1;

	@XmlAttribute(name = "id")
	private Long id;

	@XmlAttribute(name = "borrower-name")
	private String borrowerName;

	@XmlAttribute(name = "borrower-ssn")
	private String borrowerSsn;

	@XmlAttribute(name = "credit-history")
	private Integer creditHistory;

	@XmlAttribute(name = "credit-score")
	private Integer creditScore;

	@XmlAttribute(name = "loan-amount")
	private Double loanAmount;

	@XmlAttribute(name = "loan-duration")
	private Integer loanDuration;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBorrowerName() {
		return borrowerName;
	}

	public void setBorrowerName(String borrowerName) {
		this.borrowerName = borrowerName;
	}

	public String getBorrowerSsn() {
		return borrowerSsn;
	}

	public void setBorrowerSsn(String borrowerSsn) {
		this.borrowerSsn = borrowerSsn;
	}

	public Integer getCreditHistory() {
		return creditHistory;
	}

	public void setCreditHistory(Integer creditHistory) {
		this.creditHistory = creditHistory;
	}

	public Integer getCreditScore() {
		return creditScore;
	}

	public void setCreditScore(Integer creditScore) {
		this.creditScore = creditScore;
	}

	public Double getLoanAmount() {
		return loanAmount;
	}

	public void setLoanAmount(Double loanAmount) {
		this.loanAmount = loanAmount;
	}

	public Integer getLoanDuration() {
		return loanDuration;
	}

	public void setLoanDuration(Integer loanDuration) {
		this.loanDuration = loanDuration;
	}

	public boolean equals(Object object) {
		if (object == null)
			return false;
		if (!object.getClass().isAssignableFrom(this.getClass()))
			return false;
		BankLoanQuoteRequest other = (BankLoanQuoteRequest) object;
		if (this.getId() == null || other.getId() == null)
			return this == other;
		if (this.getId().equals(other.getId()))
				return false;
		return true;
	}

	public int hashCode() {
		if (getId() != null)
			return getId().hashCode();
		return 0;
	}

}