//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 07:14:59 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.aries.org/bank/0.0.1")
package org.aries.bank._0_0;
