//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.27 at 07:14:59 PM PDT 
//


package template1.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Division.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Division">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="YWD"/>
 *     &lt;enumeration value="YMD"/>
 *     &lt;enumeration value="YD"/>
 *     &lt;enumeration value="WD"/>
 *     &lt;enumeration value="MD"/>
 *     &lt;enumeration value="ALL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Division")
@XmlEnum
public enum Division {

    NONE,
    YWD,
    YMD,
    YD,
    WD,
    MD,
    ALL;

    public String value() {
        return name();
    }

    public static Division fromValue(String v) {
        return valueOf(v);
    }

}
