package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "ActivityGroupName")
@XmlEnum
public enum ActivityGroupName {

	none,
	YouthMusicCorp,
	FifeAndDrumCorp,
	Byakuren,
	SokaGroup,
	Gajokai,
	ChorusGroup,
	StudyGroup,
	PhoneToban,
	BookstoreToban,
	CleanupCommittee,
	BuildingCommittee,
	WelcomingCommittee,
	GoldenStageCrew,
	YouthPeaceGroup,
	YouthSupportGroup,
	SokaSpiritGroup,
	CultureDept,
	Secretariet,
	CentralExecutiveCommittee;

	public ActivityGroupName fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}