package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "ActivityGroup")
@XmlEnum
public enum ActivityGroup {

	NONE,
	YOUTHMUSICCORP,
	FIFEANDDRUMCORP,
	BYAKUREN,
	SOKAGROUP,
	GAJOKAI,
	CHORUSGROUP,
	STUDYGROUP,
	PHONETOBAN,
	BOOKSTORETOBAN,
	CLEANUPCOMMITTEE,
	BUILDINGCOMMITTEE,
	WELCOMINGCOMMITTEE,
	GOLDENSTAGECREW,
	YOUTHPEACEGROUP,
	YOUTHSUPPORTGROUP,
	SOKASPIRITGROUP,
	CULTUREDEPT,
	SECRETARIET,
	CENTRALEXECUTIVECOMMITTEE;

	public ActivityGroup fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}