package org.sgiusa.model;

import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.sgiusa.model.ActivityGroup;
import org.sgiusa.model.Division;
import org.sgiusa.model.Organization;
import org.sgiusa.model.SubDivision;
import org.sgiusa.model.User;

/**
 * Generated by Nam.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmailList", propOrder = {
	"id",
	"enabled",
	"divisions",
	"subDivisions",
	"activityGroups",
	"organization",
	"emailAddressList"
})
@XmlRootElement(name = "emailList")
public class EmailList implements Serializable {

	public static final long serialVersionUID = 1;

	@XmlAttribute(name = "id")
	private Long id;

	@XmlAttribute(name = "enabled")
	private Boolean enabled;

	@XmlAttribute(name = "divisions")
	private List<Division> divisions;

	@XmlAttribute(name = "sub-divisions")
	private List<SubDivision> subDivisions;

	@XmlAttribute(name = "activity-groups")
	private List<ActivityGroup> activityGroups;

	@XmlElement(name = "organization")
	private Organization organization;

	@XmlElement(name = "email-address-list")
	private List<User> emailAddressList;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public List<Division> getDivisions() {
		return divisions;
	}

	public void setDivisions(List<Division> divisions) {
		this.divisions = divisions;
	}

	public List<SubDivision> getSubDivisions() {
		return subDivisions;
	}

	public void setSubDivisions(List<SubDivision> subDivisions) {
		this.subDivisions = subDivisions;
	}

	public List<ActivityGroup> getActivityGroups() {
		return activityGroups;
	}

	public void setActivityGroups(List<ActivityGroup> activityGroups) {
		this.activityGroups = activityGroups;
	}

	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public List<User> getEmailAddressList() {
		return emailAddressList;
	}

	public void setEmailAddressList(List<User> emailAddressList) {
		this.emailAddressList = emailAddressList;
	}

	public boolean equals(Object object) {
		if (object == null)
			return false;
		if (!object.getClass().isAssignableFrom(this.getClass()))
			return false;
		EmailList other = (EmailList) object;
		if (this.getId() == null || other.getId() == null)
			return this == other;
		if (this.getId().equals(other.getId()))
				return false;
		return true;
	}

	public int hashCode() {
		if (getId() != null)
			return getId().hashCode();
		return 0;
	}

}