package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "FamilyRelation")
@XmlEnum
public enum FamilyRelation {

	MOTHER,
	FATHER,
	SISTER,
	BROTHER,
	STEPSISTER,
	STEPBROTHER,
	HUSBAND,
	WIFE,
	SON,
	DAUGHTER,
	GRANDMOTHER,
	GRANDFATHER,
	GRANDSON,
	GRANDDAUGHTER,
	MOTHERINLAW,
	FATHERINLAW,
	SONINLAW,
	DAUGHTERINLAW,
	AUNT,
	UNCLE,
	COUSIN,
	NIECE,
	NEPHEW,
	EXHUSBAND,
	EXWIFE,
	OTHER;

	public FamilyRelation fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}