package org.sgiusa.model;

import java.io.Serializable;
import java.lang.String;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.sgiusa.model.FamilyRelation;

/**
 * Generated by Nam.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FamilyMember", propOrder = {
	"id",
	"sgiMember",
	"familyRelation",
	"personName",
	"lastUpdate"
})
@XmlRootElement(name = "familyMember")
public class FamilyMember implements Serializable {

	public static final long serialVersionUID = 1;

	@XmlAttribute(name = "id")
	private Long id;

	@XmlAttribute(name = "sgi-member")
	private Boolean sgiMember;

	@XmlAttribute(name = "family-relation")
	private FamilyRelation familyRelation;

	@XmlAttribute(name = "person-name")
	private String personName;

	@XmlAttribute(name = "last-update")
	private Date lastUpdate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getSgiMember() {
		return sgiMember;
	}

	public void setSgiMember(Boolean sgiMember) {
		this.sgiMember = sgiMember;
	}

	public FamilyRelation getFamilyRelation() {
		return familyRelation;
	}

	public void setFamilyRelation(FamilyRelation familyRelation) {
		this.familyRelation = familyRelation;
	}

	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public boolean equals(Object object) {
		if (object == null)
			return false;
		if (!object.getClass().isAssignableFrom(this.getClass()))
			return false;
		FamilyMember other = (FamilyMember) object;
		if (this.getId() == null || other.getId() == null)
			return this == other;
		if (this.getId().equals(other.getId()))
				return false;
		return true;
	}

	public int hashCode() {
		if (getId() != null)
			return getId().hashCode();
		return 0;
	}

}