package org.sgiusa.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.sgiusa.model.LeadershipRole;

/**
 * Generated by Nam.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LeadershipInfo", propOrder = {
	"id",
	"examPassed",
	"examPassedDate",
	"manualSigned",
	"manualSignedDate",
	"lastUpdate",
	"leadershipRoles"
})
@XmlRootElement(name = "leadershipInfo")
public class LeadershipInfo implements Serializable {

	public static final long serialVersionUID = 1;

	@XmlAttribute(name = "id")
	private Long id;

	@XmlAttribute(name = "exam-passed")
	private Boolean examPassed;

	@XmlAttribute(name = "exam-passed-date")
	private Date examPassedDate;

	@XmlAttribute(name = "manual-signed")
	private Boolean manualSigned;

	@XmlAttribute(name = "manual-signed-date")
	private Date manualSignedDate;

	@XmlAttribute(name = "last-update")
	private Date lastUpdate;

	@XmlElement(name = "leadership-roles")
	private List<LeadershipRole> leadershipRoles;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getExamPassed() {
		return examPassed;
	}

	public void setExamPassed(Boolean examPassed) {
		this.examPassed = examPassed;
	}

	public Date getExamPassedDate() {
		return examPassedDate;
	}

	public void setExamPassedDate(Date examPassedDate) {
		this.examPassedDate = examPassedDate;
	}

	public Boolean getManualSigned() {
		return manualSigned;
	}

	public void setManualSigned(Boolean manualSigned) {
		this.manualSigned = manualSigned;
	}

	public Date getManualSignedDate() {
		return manualSignedDate;
	}

	public void setManualSignedDate(Date manualSignedDate) {
		this.manualSignedDate = manualSignedDate;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public List<LeadershipRole> getLeadershipRoles() {
		return leadershipRoles;
	}

	public void setLeadershipRoles(List<LeadershipRole> leadershipRoles) {
		this.leadershipRoles = leadershipRoles;
	}

	public boolean equals(Object object) {
		if (object == null)
			return false;
		if (!object.getClass().isAssignableFrom(this.getClass()))
			return false;
		LeadershipInfo other = (LeadershipInfo) object;
		if (this.getId() == null || other.getId() == null)
			return this == other;
		if (this.getId().equals(other.getId()))
				return false;
		return true;
	}

	public int hashCode() {
		if (getId() != null)
			return getId().hashCode();
		return 0;
	}

}