package org.sgiusa.model;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.sgiusa.model.ActivityGroup;
import org.sgiusa.model.Division;
import org.sgiusa.model.OrganizationLevel;
import org.sgiusa.model.Position;
import org.sgiusa.model.SubDivision;

/**
 * Generated by Nam.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LeadershipRole", propOrder = {
	"id",
	"active",
	"level",
	"position",
	"division",
	"subDivision",
	"activityGroup",
	"startDate",
	"endDate",
	"lastUpdate"
})
@XmlRootElement(name = "leadershipRole")
public class LeadershipRole implements Serializable {

	public static final long serialVersionUID = 1;

	@XmlAttribute(name = "id")
	private Long id;

	@XmlAttribute(name = "active")
	private Boolean active;

	@XmlAttribute(name = "level")
	private OrganizationLevel level;

	@XmlAttribute(name = "position")
	private Position position;

	@XmlAttribute(name = "division")
	private Division division;

	@XmlAttribute(name = "sub-division")
	private SubDivision subDivision;

	@XmlAttribute(name = "activity-group")
	private ActivityGroup activityGroup;

	@XmlAttribute(name = "start-date")
	private Date startDate;

	@XmlAttribute(name = "end-date")
	private Date endDate;

	@XmlAttribute(name = "last-update")
	private Date lastUpdate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public OrganizationLevel getLevel() {
		return level;
	}

	public void setLevel(OrganizationLevel level) {
		this.level = level;
	}

	public Position getPosition() {
		return position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public Division getDivision() {
		return division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	public SubDivision getSubDivision() {
		return subDivision;
	}

	public void setSubDivision(SubDivision subDivision) {
		this.subDivision = subDivision;
	}

	public ActivityGroup getActivityGroup() {
		return activityGroup;
	}

	public void setActivityGroup(ActivityGroup activityGroup) {
		this.activityGroup = activityGroup;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public boolean equals(Object object) {
		if (object == null)
			return false;
		if (!object.getClass().isAssignableFrom(this.getClass()))
			return false;
		LeadershipRole other = (LeadershipRole) object;
		if (this.getId() == null || other.getId() == null)
			return this == other;
		if (this.getId().equals(other.getId()))
				return false;
		return true;
	}

	public int hashCode() {
		if (getId() != null)
			return getId().hashCode();
		return 0;
	}

}