package org.sgiusa.model;

import java.io.Serializable;
import java.lang.String;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.sgiusa.model.Organization;
import org.sgiusa.model.OrganizationLevel;
import org.sgiusa.model.User;

/**
 * Generated by Nam.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organization", propOrder = {
	"id",
	"organizationId",
	"type",
	"level",
	"name",
	"abbrv",
	"zipCodes",
	"creationDate",
	"lastUpdate",
	"parent",
	"children",
	"creator",
	"provider",
	"accessors"
})
@XmlRootElement(name = "organization")
public class Organization implements Serializable {

	public static final long serialVersionUID = 1;

	@XmlAttribute(name = "id")
	private Long id;

	@XmlAttribute(name = "organization-id")
	private String organizationId;

	@XmlAttribute(name = "type")
	private String type;

	@XmlAttribute(name = "level")
	private OrganizationLevel level;

	@XmlAttribute(name = "name")
	private String name;

	@XmlAttribute(name = "abbrv")
	private String abbrv;

	@XmlAttribute(name = "zip-codes")
	private List<String> zipCodes;

	@XmlAttribute(name = "creation-date")
	private Date creationDate;

	@XmlAttribute(name = "last-update")
	private Date lastUpdate;

	@XmlElement(name = "parent")
	private Organization parent;

	@XmlElement(name = "children")
	private List<Organization> children;

	@XmlElement(name = "creator")
	private User creator;

	@XmlElement(name = "provider")
	private User provider;

	@XmlElement(name = "accessors")
	private List<User> accessors;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public OrganizationLevel getLevel() {
		return level;
	}

	public void setLevel(OrganizationLevel level) {
		this.level = level;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAbbrv() {
		return abbrv;
	}

	public void setAbbrv(String abbrv) {
		this.abbrv = abbrv;
	}

	public List<String> getZipCodes() {
		return zipCodes;
	}

	public void setZipCodes(List<String> zipCodes) {
		this.zipCodes = zipCodes;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Organization getParent() {
		return parent;
	}

	public void setParent(Organization parent) {
		this.parent = parent;
	}

	public List<Organization> getChildren() {
		return children;
	}

	public void setChildren(List<Organization> children) {
		this.children = children;
	}

	public User getCreator() {
		return creator;
	}

	public void setCreator(User creator) {
		this.creator = creator;
	}

	public User getProvider() {
		return provider;
	}

	public void setProvider(User provider) {
		this.provider = provider;
	}

	public List<User> getAccessors() {
		return accessors;
	}

	public void setAccessors(List<User> accessors) {
		this.accessors = accessors;
	}

	public boolean equals(Object object) {
		if (object == null)
			return false;
		if (!object.getClass().isAssignableFrom(this.getClass()))
			return false;
		Organization other = (Organization) object;
		if (this.getOrganizationId() == null || other.getOrganizationId() == null || 
			this.getId() == null || other.getId() == null)
			return this == other;
		if (this.getOrganizationId().equals(other.getOrganizationId()) && 
			this.getId().equals(other.getId()))
				return false;
		return true;
	}

	public int hashCode() {
		if (getOrganizationId() != null)
			return getOrganizationId().hashCode();
		return 0;
	}

}