package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "SchoolType")
@XmlEnum
public enum SchoolType {

	ELEMENTARY,
	GRAMMER,
	JRHIGHSCHOOL,
	HIGHSCHOOL,
	COLLEGE,
	GRADUATE,
	OTHER;

	public SchoolType fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}