package org.sgiusa.model;

import java.io.Serializable;
import java.lang.String;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.sgiusa.model.StudyDeptExamLevel;
import org.sgiusa.model.StudyDeptLanguage;

/**
 * Generated by Nam.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudyDeptExam", propOrder = {
	"id",
	"current",
	"examLevel",
	"examLanguage",
	"examLocation",
	"examDate",
	"lastUpdate"
})
@XmlRootElement(name = "studyDeptExam")
public class StudyDeptExam implements Serializable {

	public static final long serialVersionUID = 1;

	@XmlAttribute(name = "id")
	private Long id;

	@XmlAttribute(name = "current")
	private Boolean current;

	@XmlAttribute(name = "exam-level")
	private StudyDeptExamLevel examLevel;

	@XmlAttribute(name = "exam-language")
	private StudyDeptLanguage examLanguage;

	@XmlAttribute(name = "exam-location")
	private String examLocation;

	@XmlAttribute(name = "exam-date")
	private Date examDate;

	@XmlAttribute(name = "last-update")
	private Date lastUpdate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getCurrent() {
		return current;
	}

	public void setCurrent(Boolean current) {
		this.current = current;
	}

	public StudyDeptExamLevel getExamLevel() {
		return examLevel;
	}

	public void setExamLevel(StudyDeptExamLevel examLevel) {
		this.examLevel = examLevel;
	}

	public StudyDeptLanguage getExamLanguage() {
		return examLanguage;
	}

	public void setExamLanguage(StudyDeptLanguage examLanguage) {
		this.examLanguage = examLanguage;
	}

	public String getExamLocation() {
		return examLocation;
	}

	public void setExamLocation(String examLocation) {
		this.examLocation = examLocation;
	}

	public Date getExamDate() {
		return examDate;
	}

	public void setExamDate(Date examDate) {
		this.examDate = examDate;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public boolean equals(Object object) {
		if (object == null)
			return false;
		if (!object.getClass().isAssignableFrom(this.getClass()))
			return false;
		StudyDeptExam other = (StudyDeptExam) object;
		if (this.getId() == null || other.getId() == null)
			return this == other;
		if (this.getId().equals(other.getId()))
				return false;
		return true;
	}

	public int hashCode() {
		if (getId() != null)
			return getId().hashCode();
		return 0;
	}

}