package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "StudyDeptExamLevel")
@XmlEnum
public enum StudyDeptExamLevel {

	ENTRANCE,
	ELEMENTARY,
	INTERMEDIATE,
	ADVANCED,
	GRADUATE,
	POSTGRADUATE,
	OTHER;

	public StudyDeptExamLevel fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}