package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "StudyDeptLanguage")
@XmlEnum
public enum StudyDeptLanguage {

	ENGLISH,
	SPANISH,
	FRENCH,
	ITALIAN,
	GERMAN,
	PORTUGUESE,
	JAPANESE,
	CHINESE,
	KOREAN,
	VIETNAMESE,
	THAI,
	OTHER;

	public StudyDeptLanguage fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}