package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "SubDivisionName")
@XmlEnum
public enum SubDivisionName {

	StudentDivision,
	HighSchoolDivision,
	JrHighSchoolDivision,
	ElementarySchoolDivision,
	ChildrenSDivision,
	ALLSubDivisions;

	public SubDivisionName fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}