package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "SubDivision")
@XmlEnum
public enum SubDivision {

	STUDENT,
	HIGHSCHOOL,
	JRHIGHSCHOOL,
	ELEMENTARYSCHOOL,
	CHILDREN,
	ALL;

	public SubDivision fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}