package org.sgiusa.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "UserRole")
@XmlEnum
public enum UserRole {

	USER,
	HOST,
	MANAGER;

	public UserRole fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}