package org.sgiusa.model;

import java.io.Serializable;
import java.lang.String;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.sgiusa.model.ActivityGroup;
import org.sgiusa.model.Division;
import org.sgiusa.model.Organization;
import org.sgiusa.model.SubDivision;
import org.sgiusa.model.UserOperation;
import org.sgiusa.model.UserRole;

/**
 * Generated by Nam.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserPermission", propOrder = {
	"id",
	"userId",
	"enabled",
	"divisions",
	"subDivisions",
	"activityGroups",
	"userRoles",
	"userOperations",
	"organization"
})
@XmlRootElement(name = "userPermission")
public class UserPermission implements Serializable {

	public static final long serialVersionUID = 1;

	@XmlAttribute(name = "id")
	private Long id;

	@XmlAttribute(name = "user-id")
	private String userId;

	@XmlAttribute(name = "enabled")
	private Boolean enabled;

	@XmlAttribute(name = "divisions")
	private List<Division> divisions;

	@XmlAttribute(name = "sub-divisions")
	private List<SubDivision> subDivisions;

	@XmlAttribute(name = "activity-groups")
	private List<ActivityGroup> activityGroups;

	@XmlAttribute(name = "user-roles")
	private List<UserRole> userRoles;

	@XmlAttribute(name = "user-operations")
	private List<UserOperation> userOperations;

	@XmlElement(name = "organization")
	private Organization organization;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public List<Division> getDivisions() {
		return divisions;
	}

	public void setDivisions(List<Division> divisions) {
		this.divisions = divisions;
	}

	public List<SubDivision> getSubDivisions() {
		return subDivisions;
	}

	public void setSubDivisions(List<SubDivision> subDivisions) {
		this.subDivisions = subDivisions;
	}

	public List<ActivityGroup> getActivityGroups() {
		return activityGroups;
	}

	public void setActivityGroups(List<ActivityGroup> activityGroups) {
		this.activityGroups = activityGroups;
	}

	public List<UserRole> getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(List<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	public List<UserOperation> getUserOperations() {
		return userOperations;
	}

	public void setUserOperations(List<UserOperation> userOperations) {
		this.userOperations = userOperations;
	}

	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public boolean equals(Object object) {
		if (object == null)
			return false;
		if (!object.getClass().isAssignableFrom(this.getClass()))
			return false;
		UserPermission other = (UserPermission) object;
		if (this.getId() == null || other.getId() == null || 
			this.getUserId() == null || other.getUserId() == null)
			return this == other;
		if (this.getId().equals(other.getId()) && 
			this.getUserId().equals(other.getUserId()))
				return false;
		return true;
	}

	public int hashCode() {
		if (getId() != null)
			return getId().hashCode();
		return 0;
	}

}