 package simpleinvoke.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * Generated by Nam.
 *
 */
//@WebService
@WebService(targetNamespace = "http://www.aries.org/simple_invoke/helloworld", name = "HelloWorldWS")
//@WebService(name = "HelloWorldWS", serviceName = "HelloWorldWSService", portName = "HelloWorldWSPort", targetNamespace = "http://www.aries.org/simple_invoke/helloworld")
//@SOAPBinding(style = Style.DOCUMENT, use=Use.LITERAL)
@SOAPBinding(style=SOAPBinding.Style.RPC)
public interface HelloWorldWS {

	@WebMethod
	@WebResult(name = "response")
	//@WebResult(targetNamespace = "http://www.aries.org/simple_invoke/helloworld", partName = "response")
	//@RequestWrapper(targetNamespace="http://www.aries.org/simple_invoke/helloworld", className="simpleinvoke.helloworld.SayHello")
	//@ResponseWrapper(targetNamespace="http://www.aries.org/simple_invoke/helloworld", className="simpleinvoke.helloworld.SayHelloResponse")
	public SayHelloResponse sayHello(@WebParam(targetNamespace = "http://www.aries.org/simple_invoke/helloworld", name = "request") SayHello sayHello);

	@WebMethod
	@WebResult(name = "response")
	public SayGoodbyeResponse sayGoodbye(@WebParam(name = "request") SayGoodbye sayGoodbye);

}
