package org.aries.bank;

import javax.jws.WebService;
import javax.xml.ws.WebServiceRef;

import org.aries.bank.BankLoanQuoteRequest;
import org.aries.bank.BankLoanQuoteResponse;

/**
 * Generated by Nam.
 *
 */
@WebService(name = "BankLoanQuote", serviceName = "BankLoanQuoteService", portName = "BankLoanQuotePort", targetNamespace = "http://www.aries.org/bank/0.0.1")
public class BankLoanQuoteClient implements BankLoanQuote {

	@WebServiceRef(wsdlLocation="http://localhost:8080/bank/0.0.1?wsdl")
	private BankLoanQuoteStub service;

	@Override
	public BankLoanQuoteResponse getLoanQuote(BankLoanQuoteRequest request) {
		service = new BankLoanQuoteStub();
		BankLoanQuote port = service.getBankLoanQuotePort();
		BankLoanQuoteResponse response = port.getLoanQuote(request);
		return response;
	}

}
