package org.aries.bank;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * Generated by Nam.
 *
 */
@WebServiceClient(name = "BankLoanQuoteService", targetNamespace = "http://www.aries.org/bank/0.0.1", wsdlLocation = "http://localhost:8080/bank/0.0.1?wsdl")
public class BankLoanQuoteStub extends Service {

	public static URL createWsdlLocationUrl() {
		try {
			URL url = new URL("http://localhost:8080/bank/0.0.1?wsdl");
			return url;
		} catch (MalformedURLException e) {
			e.printStackTrace();
			return null;
		}
	}

	public static QName getServiceQName() {
		return new QName("http://www.aries.org/bank/0.0.1", "BankLoanQuoteService");
	}

	public static QName getPortQName() {
		return new QName("http://www.aries.org/bank/0.0.1", "BankLoanQuotePort");
	}

	public BankLoanQuoteStub() {
		super(createWsdlLocationUrl(), getServiceQName());
	}

	@WebEndpoint(name = "BankLoanQuotePort")
	public BankLoanQuote getBankLoanQuotePort() {
		return (BankLoanQuote) super.getPort(getPortQName(), BankLoanQuote.class);
	}

}
