package org.aries.common.entity;

import java.lang.String;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.aries.common.Country;
import org.aries.common.State;
import org.aries.common.entity.ZipCodeEntity;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.ForeignKey;

/**
 * Generated by Nam.
 *
 */
@Entity(name = "StreetAddress")
@Table(name = "street_address")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class StreetAddressEntity {

	@Id
	@GeneratedValue
	@Column(name = "id")
	private Long id;

	@Column(name = "city")
	private String city;

	@Column(name = "country")
	private Country country;

	@Column(name = "latitude")
	private Double latitude;

	@Column(name = "longitude")
	private Double longitude;

	@Column(name = "state")
	private State state;

	@Column(name = "street")
	private String street;

	@JoinColumn(name = "zip", referencedColumnName = "id")
	@OneToOne(cascade = CascadeType.ALL)
	@ForeignKey(name = "street_address_entity_zip_fk")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	private ZipCodeEntity zip;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public State getState() {
		return state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public ZipCodeEntity getZip() {
		return zip;
	}

	public void setZip(ZipCodeEntity zip) {
		this.zip = zip;
	}

}