package simpleinvoke.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.xml.ws.WebServiceRef;

/**
 * Generated by Nam.
 *
 */
//@WebService(name = "HelloWorldWS", serviceName = "HelloWorldWSService", portName = "HelloWorldWSPort", targetNamespace = "http://www.aries.org/simple_invoke/helloworld")
public class HelloWorldWSProxy implements HelloWorldWS {

	@WebServiceRef(wsdlLocation="http://localhost:8080/SimpleInvoke/HelloWorld?wsdl")
	private static HelloWorldWSStub service;

	
	//@WebMethod
	//@WebResult(name = "response")
	//@RequestWrapper(targetNamespace="http://www.aries.org/simple_invoke/helloworld", className="simpleinvoke.helloworld.SayHello")
	//@ResponseWrapper(targetNamespace="http://www.aries.org/simple_invoke/helloworld", className="simpleinvoke.helloworld.SayHelloResponse")
	public SayHelloResponse sayHello(@WebParam(name = "request") SayHello sayHello) {
		if (service == null)
			service = new HelloWorldWSStub();
		HelloWorldWS port = service.getHelloWorldWSPort();
		SayHelloResponse response = port.sayHello(sayHello);
		return response;
	}

	@WebMethod
	public SayGoodbyeResponse sayGoodbye(SayGoodbye sayGoodbye) {
		return null;
	}

}
