package simpleinvoke.helloworld;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * Generated by Nam.
 *
 */
@WebServiceClient(name = "HelloWorldWSService", targetNamespace = "http://www.aries.org/simple_invoke/helloworld", wsdlLocation = "http://localhost:8080/SimpleInvoke/HelloWorld?wsdl")
public class HelloWorldWSStub extends Service {

	public static URL createWsdlLocationUrl() {
		try {
			URL url = new URL("http://localhost:8080/SimpleInvoke/HelloWorld?wsdl");
			return url;
		} catch (MalformedURLException e) {
			e.printStackTrace();
			return null;
		}
	}

	public static QName getServiceQName() {
		return new QName("http://www.aries.org/simple_invoke/helloworld", "HelloWorldWSService");
	}

	public static QName getPortQName() {
		return new QName("http://www.aries.org/simple_invoke/helloworld", "HelloWorldWSPort");
	}

	public HelloWorldWSStub() {
		super(createWsdlLocationUrl(), getServiceQName());
	}

	@WebEndpoint(name = "HelloWorldWSPort")
	public HelloWorldWS getHelloWorldWSPort() {
		return (HelloWorldWS) super.getPort(getPortQName(), HelloWorldWS.class);
	}

}
