package simpleinvoke.helloworld;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * Generated by Nam.
 *
 */
@WebServiceClient(name = "SimpleInvokeService", targetNamespace = "http://www.jboss.org/bpel/examples/wsdl", wsdlLocation = "http://localhost:8180/SimpleInvoke?wsdl")
public class SimpleInvokeStub extends Service {

	public static URL createWsdlLocationUrl() {
		try {
			URL url = new URL("http://localhost:8180/SimpleInvoke?wsdl");
			return url;
		} catch (MalformedURLException e) {
			e.printStackTrace();
			return null;
		}
	}

	public static QName getServiceQName() {
		return new QName("http://www.jboss.org/bpel/examples/wsdl", "SimpleInvokeService");
	}

	public static QName getPortQName() {
		return new QName("http://www.jboss.org/bpel/examples/wsdl", "SimpleInvokePort");
	}

	public SimpleInvokeStub() {
		super(createWsdlLocationUrl(), getServiceQName());
	}

	@WebEndpoint(name = "SimpleInvokePort")
	public SimpleInvoke getSimpleInvokePort() {
		return (SimpleInvoke) super.getPort(getPortQName(), SimpleInvoke.class);
	}

}
