package common.tx;

import javax.xml.namespace.QName;


public class CoordinationConstants {

	public static String WSCOOR_NAMESPACE = "http://docs.oasis-open.org/ws-tx/wscoor/2006/06";
	public static String WSCOOR_PREFIX = "wscoor";

	public static String ACTIVATION_SERVICE_NAME = "ActivationService";
	public static QName ACTIVATION_SERVICE_QNAME = new QName(WSCOOR_NAMESPACE, ACTIVATION_SERVICE_NAME, WSCOOR_PREFIX);

	public static String ACTIVATION_ENDPOINT_NAME = "ActivationPortType";
	public static QName ACTIVATION_ENDPOINT_QNAME = new QName(WSCOOR_NAMESPACE, ACTIVATION_ENDPOINT_NAME, WSCOOR_PREFIX);

	public static String REGISTRATION_SERVICE_NAME = "RegistrationService";
	public static QName REGISTRATION_SERVICE_QNAME = new QName(WSCOOR_NAMESPACE, REGISTRATION_SERVICE_NAME, WSCOOR_PREFIX);

	public static String REGISTRATION_ENDPOINT_NAME = "RegistrationPortType";
	public static QName REGISTRATION_ENDPOINT_QNAME = new QName(WSCOOR_NAMESPACE, REGISTRATION_ENDPOINT_NAME, WSCOOR_PREFIX);


	public static String WSCOOR_ELEMENT_COORDINATION_CONTEXT = "CoordinationContext";
	public static QName WSCOOR_ELEMENT_COORDINATION_CONTEXT_QNAME = new QName(WSCOOR_NAMESPACE, WSCOOR_ELEMENT_COORDINATION_CONTEXT, WSCOOR_PREFIX);

	public static String WSCOOR_ELEMENT_CURRENT_CONTEXT = "CurrentContext";
	public static QName WSCOOR_ELEMENT_CURRENT_CONTEXT_QNAME = new QName(WSCOOR_NAMESPACE, WSCOOR_ELEMENT_CURRENT_CONTEXT, WSCOOR_PREFIX);

    public static String WSCOOR_ELEMENT_CREATE_COORDINATION_CONTEXT = "CreateCoordinationContext" ;
    public static String WSCOOR_ACTION_CREATE_COORDINATION_CONTEXT = WSCOOR_NAMESPACE + "/" + WSCOOR_ELEMENT_CREATE_COORDINATION_CONTEXT ;

    public static String WSCOOR_ELEMENT_REGISTER = "Register" ;
    public static String WSCOOR_ACTION_REGISTER = WSCOOR_NAMESPACE + "/" + WSCOOR_ELEMENT_REGISTER ;

	public static String WSCOOR_ERROR_CODE_ALREADY_REGISTERED = "AlreadyRegistered";
	public static QName WSCOOR_ERROR_CODE_ALREADY_REGISTERED_QNAME = new QName(WSCOOR_NAMESPACE, WSCOOR_ERROR_CODE_ALREADY_REGISTERED, WSCOOR_PREFIX);

	public static String WSCOOR_ERROR_CODE_CANNOT_REGISTER = "CannotRegister";
	public static QName WSCOOR_ERROR_CODE_CANNOT_REGISTER_QNAME = new QName(WSCOOR_NAMESPACE, WSCOOR_ERROR_CODE_CANNOT_REGISTER, WSCOOR_PREFIX);

	public static String WSCOOR_ERROR_CODE_INVALID_PROTOCOL = "InvalidProtocol";
	public static QName WSCOOR_ERROR_CODE_INVALID_PROTOCOL_QNAME = new QName(WSCOOR_NAMESPACE, WSCOOR_ERROR_CODE_INVALID_PROTOCOL, WSCOOR_PREFIX);

	public static String WSCOOR_ERROR_CODE_INVALID_STATE = "InvalidState";
	public static QName WSCOOR_ERROR_CODE_INVALID_STATE_QNAME = new QName(WSCOOR_NAMESPACE, WSCOOR_ERROR_CODE_INVALID_STATE, WSCOOR_PREFIX);


	public static String WSAT_NAMESPACE = "http://docs.oasis-open.org/ws-tx/wsat/2006/06";
	public static String WSAT_PREFIX = "wsat";
	public static String WSAT_PROTOCOL = WSAT_NAMESPACE;

	public static String COMPLETION_COORDINATOR_SERVICE_NAME = "CompletionCoordinatorService";
	public static QName COMPLETION_COORDINATOR_SERVICE_QNAME = new QName(WSAT_NAMESPACE, COMPLETION_COORDINATOR_SERVICE_NAME, WSAT_PREFIX);

	public static String COMPLETION_COORDINATOR_ENDPOINT_NAME = "CompletionCoordinatorPortType";
	public static QName COMPLETION_COORDINATOR_ENDPOINT_QNAME = new QName(WSAT_NAMESPACE, COMPLETION_COORDINATOR_ENDPOINT_NAME, WSAT_PREFIX);

	public static String COMPLETION_INITIATOR_SERVICE_NAME = "CompletionInitiatorService";
	public static QName COMPLETION_INITIATOR_SERVICE_QNAME = new QName(WSAT_NAMESPACE, COMPLETION_INITIATOR_SERVICE_NAME, WSAT_PREFIX);

	public static String COMPLETION_INITIATOR_ENDPOINT_NAME = "CompletionInitiatorPortType";
	public static QName COMPLETION_INITIATOR_ENDPOINT_QNAME = new QName(WSAT_NAMESPACE, COMPLETION_INITIATOR_ENDPOINT_NAME, WSAT_PREFIX);

	public static String COORDINATOR_SERVICE_NAME = "CoordinatorService";
	public static QName COORDINATOR_SERVICE_QNAME = new QName(WSAT_NAMESPACE, COORDINATOR_SERVICE_NAME, WSAT_PREFIX);

	public static String COORDINATOR_ENDPOINT_NAME = "CoordinatorPortType";
	public static QName COORDINATOR_PORT_QNAME = new QName(WSAT_NAMESPACE, COORDINATOR_ENDPOINT_NAME, WSAT_PREFIX);

	public static String PARTICIPANT_INSTANCE_SERVICE_NAME = "ParticipantInstanceService";
	public static QName PARTICIPANT_INSTANCE_SERVICE_QNAME = new QName(WSAT_NAMESPACE, PARTICIPANT_INSTANCE_SERVICE_NAME, WSAT_PREFIX);

	public static String PARTICIPANT_INSTANCE_ENDPOINT_NAME = "ParticipantInstancePortType";
	public static QName PARTICIPANT_INSTANCE_ENDPOINT_QNAME = new QName(WSAT_NAMESPACE, PARTICIPANT_INSTANCE_ENDPOINT_NAME, WSAT_PREFIX);

	public static String PARTICIPANT_SERVICE_NAME = "ParticipantService";
	public static QName PARTICIPANT_SERVICE_QNAME = new QName(WSAT_NAMESPACE, PARTICIPANT_SERVICE_NAME, WSAT_PREFIX);

	public static String PARTICIPANT_ENDPOINT_NAME = "ParticipantPortType";
	public static QName PARTICIPANT_ENDPOINT_QNAME = new QName(WSAT_NAMESPACE, PARTICIPANT_ENDPOINT_NAME, WSAT_PREFIX);


	public static String WSAT_ERROR_CODE_UNKNOWN_TRANSACTION = "UnknownTransaction";
	public static QName WSAT_ERROR_CODE_UNKNOWN_TRANSACTION_QNAME = new QName(WSAT_NAMESPACE, WSAT_ERROR_CODE_UNKNOWN_TRANSACTION, WSAT_PREFIX);

	public static String ERROR_CODE_UNKNOWN_PARTICIPANT = "UnknownParticipant";
	public static QName ERROR_CODE_UNKNOWN_PARTICIPANT_QNAME = new QName(WSAT_NAMESPACE, ERROR_CODE_UNKNOWN_PARTICIPANT, WSAT_PREFIX);

	public static String ERROR_CODE_NO_ACTIVITY = "NoActivity";
	public static QName ERROR_CODE_NO_ACTIVITY_QNAME = new QName(WSAT_NAMESPACE, ERROR_CODE_NO_ACTIVITY, WSAT_PREFIX);

	public static String ERROR_CODE_UNKNOWN_COORDINATION_TYPE = "UnknownCoordinationType";
	public static QName ERROR_CODE_UNKNOWN_COORDINATION_TYPE_QNAME = new QName(WSAT_NAMESPACE, ERROR_CODE_UNKNOWN_COORDINATION_TYPE, WSAT_PREFIX);

	public static String ERROR_CODE_UNKNOWN_PROTOCOL_ID = "UnknownProtocolId";
	public static QName ERROR_CODE_UNKNOWN_PROTOCOL_ID_QNAME = new QName(WSAT_NAMESPACE, ERROR_CODE_UNKNOWN_PROTOCOL_ID, WSAT_PREFIX);

	public static String WSAT_ERROR_CODE_INCONSISTENT_INTERNAL_STATE = "InconsistentInternalState";
	public static QName WSAT_ERROR_CODE_INCONSISTENT_INTERNAL_STATE_QNAME = new QName(WSAT_NAMESPACE, WSAT_ERROR_CODE_INCONSISTENT_INTERNAL_STATE, WSAT_PREFIX);

	public static String ERROR_CODE_SYSTEM_EXCEPTION = "SystemException";
	public static QName ERROR_CODE_SYSTEM_EXCEPTION_QNAME = new QName(WSAT_NAMESPACE, ERROR_CODE_SYSTEM_EXCEPTION, WSAT_PREFIX);

	public static String ERROR_CODE_UNEXPECTED_ERROR = "UnexpectedError";
	public static QName ERROR_CODE_UNEXPECTED_ERROR_QNAME = new QName(WSAT_NAMESPACE, ERROR_CODE_UNEXPECTED_ERROR, WSAT_PREFIX);

	
	public static String WSAT_SUB_PROTOCOL_COMPLETION = WSAT_NAMESPACE + "/Completion";
	public static String WSAT_SUB_PROTOCOL_DURABLE_2PC = WSAT_NAMESPACE + "/Durable2PC";
	public static String WSAT_SUB_PROTOCOL_VOLATILE_2PC = WSAT_NAMESPACE + "/Volatile2PC";


	public static String WSARJ_NAMESPACE = "http://schemas.arjuna.com/ws/2005/10/wsarj";
	public static String WSARJ_PREFIX = "wsarj";

	public static String WSARJ_ELEMENT_INSTANCE_IDENTIFIER = "InstanceIdentifier";
	public static QName WSARJ_ELEMENT_INSTANCE_IDENTIFIER_QNAME = new QName(WSARJ_NAMESPACE, WSARJ_ELEMENT_INSTANCE_IDENTIFIER, WSARJ_PREFIX);

}
