//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 01:45:53 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.aries.org/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.aries.common;
