package org.sgiusa.model.entity;

import java.lang.String;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.sgiusa.model.FamilyRelation;

/**
 * Generated by Nam.
 *
 */
@Entity(name = "FamilyMember")
@Table(name = "family_member")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class FamilyMemberEntity {

	@Id
	@GeneratedValue
	@Column(name = "id")
	private Long id;

	@Column(name = "sgi_member")
	private Boolean sgiMember;

	@Column(name = "family_relation")
	private FamilyRelation familyRelation;

	@Column(name = "person_name")
	private String personName;

	@Column(name = "last_update")
	@Temporal(TemporalType.TIMESTAMP)
	private Date lastUpdate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getSgiMember() {
		return sgiMember;
	}

	public void setSgiMember(Boolean sgiMember) {
		this.sgiMember = sgiMember;
	}

	public FamilyRelation getFamilyRelation() {
		return familyRelation;
	}

	public void setFamilyRelation(FamilyRelation familyRelation) {
		this.familyRelation = familyRelation;
	}

	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}