package org.sgiusa.model.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.sgiusa.model.GohonzonType;

/**
 * Generated by Nam.
 *
 */
@Entity(name = "GohonzonInfo")
@Table(name = "gohonzon_info")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class GohonzonInfoEntity {

	@Id
	@GeneratedValue
	@Column(name = "id")
	private Long id;

	@Column(name = "gohonzon_type")
	private GohonzonType gohonzonType;

	@Column(name = "receive_date")
	@Temporal(TemporalType.TIMESTAMP)
	private Date receiveDate;

	@Column(name = "returned")
	private Boolean returned;

	@Column(name = "return_date")
	@Temporal(TemporalType.TIMESTAMP)
	private Date returnDate;

	@Column(name = "last_update")
	@Temporal(TemporalType.TIMESTAMP)
	private Date lastUpdate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public GohonzonType getGohonzonType() {
		return gohonzonType;
	}

	public void setGohonzonType(GohonzonType gohonzonType) {
		this.gohonzonType = gohonzonType;
	}

	public Date getReceiveDate() {
		return receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public Boolean getReturned() {
		return returned;
	}

	public void setReturned(Boolean returned) {
		this.returned = returned;
	}

	public Date getReturnDate() {
		return returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public Date getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}