package org.sgiusa.model.entity;

import java.lang.String;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.ForeignKey;
import org.sgiusa.model.ActivityGroup;
import org.sgiusa.model.Division;
import org.sgiusa.model.SubDivision;
import org.sgiusa.model.UserOperation;
import org.sgiusa.model.UserRole;
import org.sgiusa.model.entity.OrganizationEntity;

/**
 * Generated by Nam.
 *
 */
@Entity(name = "UserPermission")
@Table(name = "user_permission")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class UserPermissionEntity {

	@Id
	@GeneratedValue
	@Column(name = "id")
	private Long id;

	@Column(name = "user_id")
	private String userId;

	@Column(name = "enabled")
	private Boolean enabled;

	@Column(name = "divisions")
	@Enumerated(EnumType.STRING)
	@ElementCollection(targetClass = Division.class)
	@CollectionTable(name = "user_permission_division")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	private List<Division> divisions;

	@Column(name = "sub_divisions")
	@Enumerated(EnumType.STRING)
	@ElementCollection(targetClass = SubDivision.class)
	@CollectionTable(name = "user_permission_sub_division")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	private List<SubDivision> subDivisions;

	@Column(name = "activity_groups")
	@Enumerated(EnumType.STRING)
	@ElementCollection(targetClass = ActivityGroup.class)
	@CollectionTable(name = "user_permission_activity_group")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	private List<ActivityGroup> activityGroups;

	@Column(name = "user_roles")
	@Enumerated(EnumType.STRING)
	@ElementCollection(targetClass = UserRole.class)
	@CollectionTable(name = "user_permission_user_role")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	private List<UserRole> userRoles;

	@Column(name = "user_operations")
	@Enumerated(EnumType.STRING)
	@ElementCollection(targetClass = UserOperation.class)
	@CollectionTable(name = "user_permission_user_operation")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	private List<UserOperation> userOperations;

	@JoinColumn(name = "organization", referencedColumnName = "id")
	@OneToOne(cascade = CascadeType.ALL)
	@ForeignKey(name = "user_permission_entity_organization_fk")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	private OrganizationEntity organization;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public List<Division> getDivisions() {
		return divisions;
	}

	public void setDivisions(List<Division> divisions) {
		this.divisions = divisions;
	}

	public List<SubDivision> getSubDivisions() {
		return subDivisions;
	}

	public void setSubDivisions(List<SubDivision> subDivisions) {
		this.subDivisions = subDivisions;
	}

	public List<ActivityGroup> getActivityGroups() {
		return activityGroups;
	}

	public void setActivityGroups(List<ActivityGroup> activityGroups) {
		this.activityGroups = activityGroups;
	}

	public List<UserRole> getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(List<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	public List<UserOperation> getUserOperations() {
		return userOperations;
	}

	public void setUserOperations(List<UserOperation> userOperations) {
		this.userOperations = userOperations;
	}

	public OrganizationEntity getOrganization() {
		return organization;
	}

	public void setOrganization(OrganizationEntity organization) {
		this.organization = organization;
	}

}