package org.sgiusa.model.entity;

import java.lang.Long;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.ForeignKey;
import org.sgiusa.model.entity.UserEntity;

/**
 * Generated by Nam.
 *
 */
@Entity(name = "Users")
@Table(name = "users")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class UsersEntity {

	@Id
	@GeneratedValue
	@Column(name = "id", unique=true, updatable=false, nullable=false)
	private Long id;

	@JoinColumn(name = "id")
	@OneToMany(cascade = CascadeType.ALL, targetEntity = UserEntity.class)
	@ForeignKey(name = "users_entity_record_fk")
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	private List<UserEntity> record;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<UserEntity> getRecord() {
		return record;
	}

	public void setRecord(List<UserEntity> record) {
		this.record = record;
	}

}