//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.03 at 02:07:45 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/ws-tx/wsat/2006/06")
package org.oasis_open.docs.ws_tx.wsat._2006._06;
