//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.13 at 09:55:44 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.aries.org/security", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.aries.security;
