package admin.map;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.Local;
import javax.ejb.Stateless;

import org.aries.data.map.AbstractMapper;

import admin.Skin;
import admin.entity.SkinEntity;


@Stateless
@Local(SkinMapper.class)
public class SkinMapper extends AbstractMapper<Skin, SkinEntity> {
	
	@PostConstruct
	public void initialize() {
		setModelClass(Skin.class);
		setEntityClass(SkinEntity.class);
	}
	
	public Skin toModel(SkinEntity skinEntity) {
		if (skinEntity == null)
			return null;
		Skin skinModel = createModel();
		skinModel.setId(skinEntity.getId());
		skinModel.setName(skinEntity.getName());
		skinModel.setWidth(skinEntity.getWidth());
		skinModel.setHeight(skinEntity.getHeight());
		skinModel.setMargin(skinEntity.getMargin());
		skinModel.setMarginTop(skinEntity.getMarginTop());
		skinModel.setMarginLeft(skinEntity.getMarginLeft());
		skinModel.setMarginRight(skinEntity.getMarginRight());
		skinModel.setMarginBottom(skinEntity.getMarginBottom());
		skinModel.setPadding(skinEntity.getPadding());
		skinModel.setPaddingTop(skinEntity.getPaddingTop());
		skinModel.setPaddingLeft(skinEntity.getPaddingLeft());
		skinModel.setPaddingRight(skinEntity.getPaddingRight());
		skinModel.setPaddingBottom(skinEntity.getPaddingBottom());
		skinModel.setBorderStyle(skinEntity.getBorderStyle());
		skinModel.setBorderWidth(skinEntity.getBorderWidth());
		skinModel.setBorderColor(skinEntity.getBorderColor());
		skinModel.setCornerRadius(skinEntity.getCornerRadius());
		skinModel.setBackgroundColor(skinEntity.getBackgroundColor());
		skinModel.setBackgroundImage(skinEntity.getBackgroundImage());
		skinModel.setGradientColor(skinEntity.getGradientColor());
		skinModel.setGradientImage(skinEntity.getGradientImage());
		skinModel.setFontSize(skinEntity.getFontSize());
		skinModel.setFontFamily(skinEntity.getFontFamily());
		skinModel.setFontWeight(skinEntity.getFontWeight());
		skinModel.setFontStyle(skinEntity.getFontStyle());
		skinModel.setFontVariant(skinEntity.getFontVariant());
		skinModel.setTextColor(skinEntity.getTextColor());
		skinModel.setTextDecoration(skinEntity.getTextDecoration());
		skinModel.setLinkColor(skinEntity.getLinkColor());
		skinModel.setLinkHoverColor(skinEntity.getLinkHoverColor());
		skinModel.setLinkVisitedColor(skinEntity.getLinkVisitedColor());
		skinModel.setButtonFontFamily(skinEntity.getButtonFontFamily());
		skinModel.setButtonFontSize(skinEntity.getButtonFontSize());
		skinModel.setButtonFontStyle(skinEntity.getButtonFontStyle());
		skinModel.setButtonFontVariant(skinEntity.getButtonFontVariant());
		skinModel.setButtonFontWeight(skinEntity.getButtonFontWeight());
		skinModel.setButtonTextColor(skinEntity.getButtonTextColor());
		skinModel.setButtonTextDecoration(skinEntity.getButtonTextDecoration());
		skinModel.setButtonBackgroundColor(skinEntity.getButtonBackgroundColor());
		skinModel.setButtonBackgroundImage(skinEntity.getButtonBackgroundImage());
		skinModel.setButtonGradientColor(skinEntity.getButtonGradientColor());
		skinModel.setButtonBorderStyle(skinEntity.getButtonBorderStyle());
		skinModel.setButtonBorderWidth(skinEntity.getButtonBorderWidth());
		skinModel.setButtonBorderColor(skinEntity.getButtonBorderColor());
		skinModel.setButtonControlColor(skinEntity.getButtonControlColor());
		skinModel.setButtonCornerRadius(skinEntity.getButtonCornerRadius());
		skinModel.setHeaderBackgroundColor(skinEntity.getHeaderBackgroundColor());
		skinModel.setHeaderBackgroundImage(skinEntity.getHeaderBackgroundImage());
		skinModel.setHeaderGradientColor(skinEntity.getHeaderGradientColor());
		skinModel.setHeaderBorderStyle(skinEntity.getHeaderBorderStyle());
		skinModel.setHeaderBorderWidth(skinEntity.getHeaderBorderWidth());
		skinModel.setHeaderBorderColor(skinEntity.getHeaderBorderColor());
		skinModel.setHeaderFontFamily(skinEntity.getHeaderFontFamily());
		skinModel.setHeaderFontSize(skinEntity.getHeaderFontSize());
		skinModel.setHeaderFontStyle(skinEntity.getHeaderFontStyle());
		skinModel.setHeaderFontVariant(skinEntity.getHeaderFontVariant());
		skinModel.setHeaderFontWeight(skinEntity.getHeaderFontWeight());
		skinModel.setHeaderTextColor(skinEntity.getHeaderTextColor());
		skinModel.setHeaderTextDecoration(skinEntity.getHeaderTextDecoration());
		skinModel.setToolbarBackgroundColor(skinEntity.getToolbarBackgroundColor());
		skinModel.setToolbarBackgroundImage(skinEntity.getToolbarBackgroundImage());
		skinModel.setToolbarGradientColor(skinEntity.getToolbarGradientColor());
		skinModel.setToolbarBorderColor(skinEntity.getToolbarBorderColor());
		skinModel.setToolbarBorderStyle(skinEntity.getToolbarBorderStyle());
		skinModel.setToolbarBorderWidth(skinEntity.getToolbarBorderWidth());
		skinModel.setToolbarFontFamily(skinEntity.getToolbarFontFamily());
		skinModel.setToolbarFontSize(skinEntity.getToolbarFontSize());
		skinModel.setToolbarFontStyle(skinEntity.getToolbarFontStyle());
		skinModel.setToolbarFontVariant(skinEntity.getToolbarFontVariant());
		skinModel.setToolbarFontWeight(skinEntity.getToolbarFontWeight());
		skinModel.setToolbarTextColor(skinEntity.getToolbarTextColor());
		skinModel.setToolbarTextDecoration(skinEntity.getToolbarTextDecoration());
		skinModel.setTabBackgroundColor(skinEntity.getTabBackgroundColor());
		skinModel.setTabBackgroundImage(skinEntity.getTabBackgroundImage());
		skinModel.setTabGradientColor(skinEntity.getTabGradientColor());
		skinModel.setTabBorderColor(skinEntity.getTabBorderColor());
		skinModel.setTabCornerRadius(skinEntity.getTabCornerRadius());
		skinModel.setTabFontFamily(skinEntity.getTabFontFamily());
		skinModel.setTabFontSize(skinEntity.getTabFontSize());
		skinModel.setTabFontStyle(skinEntity.getTabFontStyle());
		skinModel.setTabFontWeight(skinEntity.getTabFontWeight());
		skinModel.setTabTextColor(skinEntity.getTabTextColor());
		skinModel.setTabTextDecoration(skinEntity.getTabTextDecoration());
		skinModel.setTabActiveBackgroundColor(skinEntity.getTabActiveBackgroundColor());
		skinModel.setTabActiveBackgroundImage(skinEntity.getTabActiveBackgroundImage());
		skinModel.setTabActiveGradientColor(skinEntity.getTabActiveGradientColor());
		skinModel.setTabActiveBorderColor(skinEntity.getTabActiveBorderColor());
		skinModel.setTabActiveFontFamily(skinEntity.getTabActiveFontFamily());
		skinModel.setTabActiveFontSize(skinEntity.getTabActiveFontSize());
		skinModel.setTabActiveFontStyle(skinEntity.getTabActiveFontStyle());
		skinModel.setTabActiveFontWeight(skinEntity.getTabActiveFontWeight());
		skinModel.setTabActiveTextColor(skinEntity.getTabActiveTextColor());
		skinModel.setTabActiveTextDecoration(skinEntity.getTabActiveTextDecoration());
		skinModel.setTabInactiveBackgroundColor(skinEntity.getTabInactiveBackgroundColor());
		skinModel.setTabInactiveBackgroundImage(skinEntity.getTabInactiveBackgroundImage());
		skinModel.setTabInactiveGradientColor(skinEntity.getTabInactiveGradientColor());
		skinModel.setTabInactiveBorderColor(skinEntity.getTabInactiveBorderColor());
		skinModel.setTabInactiveFontFamily(skinEntity.getTabInactiveFontFamily());
		skinModel.setTabInactiveFontSize(skinEntity.getTabInactiveFontSize());
		skinModel.setTabInactiveFontStyle(skinEntity.getTabInactiveFontStyle());
		skinModel.setTabInactiveFontWeight(skinEntity.getTabInactiveFontWeight());
		skinModel.setTabInactiveTextColor(skinEntity.getTabInactiveTextColor());
		skinModel.setTabInactiveTextDecoration(skinEntity.getTabInactiveTextDecoration());
		skinModel.setTabDisabledBackgroundColor(skinEntity.getTabDisabledBackgroundColor());
		skinModel.setTabDisabledBackgroundImage(skinEntity.getTabDisabledBackgroundImage());
		skinModel.setTabDisabledGradientColor(skinEntity.getTabDisabledGradientColor());
		skinModel.setTabDisabledBorderColor(skinEntity.getTabDisabledBorderColor());
		skinModel.setTabDisabledFontFamily(skinEntity.getTabDisabledFontFamily());
		skinModel.setTabDisabledFontSize(skinEntity.getTabDisabledFontSize());
		skinModel.setTabDisabledFontStyle(skinEntity.getTabDisabledFontStyle());
		skinModel.setTabDisabledFontWeight(skinEntity.getTabDisabledFontWeight());
		skinModel.setTabDisabledTextColor(skinEntity.getTabDisabledTextColor());
		skinModel.setTabDisabledTextDecoration(skinEntity.getTabDisabledTextDecoration());
		skinModel.setTableBackgroundColor(skinEntity.getTableBackgroundColor());
		skinModel.setTableBorderColor(skinEntity.getTableBorderColor());
		skinModel.setTableBorderWidth(skinEntity.getTableBorderWidth());
		skinModel.setTableCellBackgroundColor(skinEntity.getTableCellBackgroundColor());
		skinModel.setTableCellBackgroundImage(skinEntity.getTableCellBackgroundImage());
		skinModel.setTableCellGradientColor(skinEntity.getTableCellGradientColor());
		skinModel.setTableCellBorderColor(skinEntity.getTableCellBorderColor());
		skinModel.setTableCellFontFamily(skinEntity.getTableCellFontFamily());
		skinModel.setTableCellFontSize(skinEntity.getTableCellFontSize());
		skinModel.setTableCellFontStyle(skinEntity.getTableCellFontStyle());
		skinModel.setTableCellFontVariant(skinEntity.getTableCellFontVariant());
		skinModel.setTableCellFontWeight(skinEntity.getTableCellFontWeight());
		skinModel.setTableCellTextColor(skinEntity.getTableCellTextColor());
		skinModel.setTableCellTextDecoration(skinEntity.getTableCellTextDecoration());
		skinModel.setTableHeaderBackgroundColor(skinEntity.getTableHeaderBackgroundColor());
		skinModel.setTableHeaderBackgroundImage(skinEntity.getTableHeaderBackgroundImage());
		skinModel.setTableHeaderGradientColor(skinEntity.getTableHeaderGradientColor());
		skinModel.setTableHeaderBorderColor(skinEntity.getTableHeaderBorderColor());
		skinModel.setTableHeaderFontFamily(skinEntity.getTableHeaderFontFamily());
		skinModel.setTableHeaderFontSize(skinEntity.getTableHeaderFontSize());
		skinModel.setTableHeaderFontStyle(skinEntity.getTableHeaderFontStyle());
		skinModel.setTableHeaderFontVariant(skinEntity.getTableHeaderFontVariant());
		skinModel.setTableHeaderFontWeight(skinEntity.getTableHeaderFontWeight());
		skinModel.setTableHeaderTextColor(skinEntity.getTableHeaderTextColor());
		skinModel.setTableHeaderTextDecoration(skinEntity.getTableHeaderTextDecoration());
		skinModel.setTableFooterBackgroundColor(skinEntity.getTableFooterBackgroundColor());
		skinModel.setTableFooterBackgroundImage(skinEntity.getTableFooterBackgroundImage());
		skinModel.setTableFooterGradientColor(skinEntity.getTableFooterGradientColor());
		skinModel.setTableFooterBorderColor(skinEntity.getTableFooterBorderColor());
		skinModel.setTableFooterFontFamily(skinEntity.getTableFooterFontFamily());
		skinModel.setTableFooterFontSize(skinEntity.getTableFooterFontSize());
		skinModel.setTableFooterFontStyle(skinEntity.getTableFooterFontStyle());
		skinModel.setTableFooterFontVariant(skinEntity.getTableFooterFontVariant());
		skinModel.setTableFooterFontWeight(skinEntity.getTableFooterFontWeight());
		skinModel.setTableFooterTextColor(skinEntity.getTableFooterTextColor());
		skinModel.setTableFooterTextDecoration(skinEntity.getTableFooterTextDecoration());
		skinModel.setTableSubHeaderBackgroundColor(skinEntity.getTableSubHeaderBackgroundColor());
		skinModel.setTableSubFooterBackgroundColor(skinEntity.getTableSubFooterBackgroundColor());
		skinModel.setTooltipBackgroundColor(skinEntity.getTooltipBackgroundColor());
		skinModel.setTooltipBackgroundImage(skinEntity.getTooltipBackgroundImage());
		skinModel.setTooltipGradientColor(skinEntity.getTooltipGradientColor());
		skinModel.setTooltipBorderColor(skinEntity.getTooltipBorderColor());
		skinModel.setTooltipBorderStyle(skinEntity.getTooltipBorderStyle());
		skinModel.setTooltipBorderWidth(skinEntity.getTooltipBorderWidth());
		skinModel.setTooltipFontFamily(skinEntity.getTooltipFontFamily());
		skinModel.setTooltipFontSize(skinEntity.getTooltipFontSize());
		skinModel.setTooltipFontStyle(skinEntity.getTooltipFontStyle());
		skinModel.setTooltipFontVariant(skinEntity.getTooltipFontVariant());
		skinModel.setTooltipFontWeight(skinEntity.getTooltipFontWeight());
		skinModel.setTooltipTextColor(skinEntity.getTooltipTextColor());
		skinModel.setTooltipTextDecoration(skinEntity.getTooltipTextDecoration());
		skinModel.setHighlightBackgroundColor(skinEntity.getHighlightBackgroundColor());
		skinModel.setHighlightBackgroundImage(skinEntity.getHighlightBackgroundImage());
		skinModel.setHighlightBorderStyle(skinEntity.getHighlightBorderStyle());
		skinModel.setHighlightBorderWidth(skinEntity.getHighlightBorderWidth());
		skinModel.setHighlightBorderColor(skinEntity.getHighlightBorderColor());
		skinModel.setHighlightFontFamily(skinEntity.getHighlightFontFamily());
		skinModel.setHighlightFontSize(skinEntity.getHighlightFontSize());
		skinModel.setHighlightFontStyle(skinEntity.getHighlightFontStyle());
		skinModel.setHighlightFontWeight(skinEntity.getHighlightFontWeight());
		skinModel.setHighlightTextColor(skinEntity.getHighlightTextColor());
		skinModel.setHighlightTextDecoration(skinEntity.getHighlightTextDecoration());
		skinModel.setHighlightControlColor(skinEntity.getHighlightControlColor());
		skinModel.setFocusBackgroundColor(skinEntity.getFocusBackgroundColor());
		skinModel.setFocusBackgroundImage(skinEntity.getFocusBackgroundImage());
		skinModel.setFocusGradientColor(skinEntity.getFocusGradientColor());
		skinModel.setFocusBorderStyle(skinEntity.getFocusBorderStyle());
		skinModel.setFocusBorderWidth(skinEntity.getFocusBorderWidth());
		skinModel.setFocusBorderColor(skinEntity.getFocusBorderColor());
		skinModel.setFocusFontFamily(skinEntity.getFocusFontFamily());
		skinModel.setFocusFontSize(skinEntity.getFocusFontSize());
		skinModel.setFocusFontStyle(skinEntity.getFocusFontStyle());
		skinModel.setFocusFontWeight(skinEntity.getFocusFontWeight());
		skinModel.setFocusTextColor(skinEntity.getFocusTextColor());
		skinModel.setFocusTextDecoration(skinEntity.getFocusTextDecoration());
		skinModel.setFocusControlColor(skinEntity.getFocusControlColor());
		skinModel.setDisabledBackgroundColor(skinEntity.getDisabledBackgroundColor());
		skinModel.setDisabledBackgroundImage(skinEntity.getDisabledBackgroundImage());
		skinModel.setDisabledBorderStyle(skinEntity.getDisabledBorderStyle());
		skinModel.setDisabledBorderWidth(skinEntity.getDisabledBorderWidth());
		skinModel.setDisabledBorderColor(skinEntity.getDisabledBorderColor());
		skinModel.setDisabledFontFamily(skinEntity.getDisabledFontFamily());
		skinModel.setDisabledFontSize(skinEntity.getDisabledFontSize());
		skinModel.setDisabledFontStyle(skinEntity.getDisabledFontStyle());
		skinModel.setDisabledFontWeight(skinEntity.getDisabledFontWeight());
		skinModel.setDisabledTextColor(skinEntity.getDisabledTextColor());
		skinModel.setDisabledTextDecoration(skinEntity.getDisabledTextDecoration());
		skinModel.setDisabledControlColor(skinEntity.getDisabledControlColor());
		skinModel.setThemeBorderColor(skinEntity.getThemeBorderColor());
		skinModel.setThemeBackgroundColor(skinEntity.getThemeBackgroundColor());
		return skinModel;
	}
	
	public List<Skin> toModelList(Collection<SkinEntity> skinEntityList) {
		if (skinEntityList == null)
			return null;
		List<Skin> skinModelList = new ArrayList<Skin>();
		for (SkinEntity skinEntity : skinEntityList) {
			Skin skinModel = toModel(skinEntity);
			skinModelList.add(skinModel);
		}
		return skinModelList;
	}
	
	public SkinEntity toEntity(Skin skinModel) {
		if (skinModel == null)
			return null;
		SkinEntity skinEntity = createEntity();
		toEntity(skinEntity, skinModel);
		return skinEntity;
	}
	
	public void toEntity(SkinEntity skinEntity, Skin skinModel) {
		if (skinEntity != null && skinModel != null) {
			skinEntity.setId(skinModel.getId());
			skinEntity.setName(skinModel.getName());
			skinEntity.setWidth(skinModel.getWidth());
			skinEntity.setHeight(skinModel.getHeight());
			skinEntity.setMargin(skinModel.getMargin());
			skinEntity.setMarginTop(skinModel.getMarginTop());
			skinEntity.setMarginLeft(skinModel.getMarginLeft());
			skinEntity.setMarginRight(skinModel.getMarginRight());
			skinEntity.setMarginBottom(skinModel.getMarginBottom());
			skinEntity.setPadding(skinModel.getPadding());
			skinEntity.setPaddingTop(skinModel.getPaddingTop());
			skinEntity.setPaddingLeft(skinModel.getPaddingLeft());
			skinEntity.setPaddingRight(skinModel.getPaddingRight());
			skinEntity.setPaddingBottom(skinModel.getPaddingBottom());
			skinEntity.setBorderStyle(skinModel.getBorderStyle());
			skinEntity.setBorderWidth(skinModel.getBorderWidth());
			skinEntity.setBorderColor(skinModel.getBorderColor());
			skinEntity.setCornerRadius(skinModel.getCornerRadius());
			skinEntity.setBackgroundColor(skinModel.getBackgroundColor());
			skinEntity.setBackgroundImage(skinModel.getBackgroundImage());
			skinEntity.setGradientColor(skinModel.getGradientColor());
			skinEntity.setGradientImage(skinModel.getGradientImage());
			skinEntity.setFontSize(skinModel.getFontSize());
			skinEntity.setFontFamily(skinModel.getFontFamily());
			skinEntity.setFontWeight(skinModel.getFontWeight());
			skinEntity.setFontStyle(skinModel.getFontStyle());
			skinEntity.setFontVariant(skinModel.getFontVariant());
			skinEntity.setTextColor(skinModel.getTextColor());
			skinEntity.setTextDecoration(skinModel.getTextDecoration());
			skinEntity.setLinkColor(skinModel.getLinkColor());
			skinEntity.setLinkHoverColor(skinModel.getLinkHoverColor());
			skinEntity.setLinkVisitedColor(skinModel.getLinkVisitedColor());
			skinEntity.setButtonFontFamily(skinModel.getButtonFontFamily());
			skinEntity.setButtonFontSize(skinModel.getButtonFontSize());
			skinEntity.setButtonFontStyle(skinModel.getButtonFontStyle());
			skinEntity.setButtonFontVariant(skinModel.getButtonFontVariant());
			skinEntity.setButtonFontWeight(skinModel.getButtonFontWeight());
			skinEntity.setButtonTextColor(skinModel.getButtonTextColor());
			skinEntity.setButtonTextDecoration(skinModel.getButtonTextDecoration());
			skinEntity.setButtonBackgroundColor(skinModel.getButtonBackgroundColor());
			skinEntity.setButtonBackgroundImage(skinModel.getButtonBackgroundImage());
			skinEntity.setButtonGradientColor(skinModel.getButtonGradientColor());
			skinEntity.setButtonBorderStyle(skinModel.getButtonBorderStyle());
			skinEntity.setButtonBorderWidth(skinModel.getButtonBorderWidth());
			skinEntity.setButtonBorderColor(skinModel.getButtonBorderColor());
			skinEntity.setButtonControlColor(skinModel.getButtonControlColor());
			skinEntity.setButtonCornerRadius(skinModel.getButtonCornerRadius());
			skinEntity.setHeaderBackgroundColor(skinModel.getHeaderBackgroundColor());
			skinEntity.setHeaderBackgroundImage(skinModel.getHeaderBackgroundImage());
			skinEntity.setHeaderGradientColor(skinModel.getHeaderGradientColor());
			skinEntity.setHeaderBorderStyle(skinModel.getHeaderBorderStyle());
			skinEntity.setHeaderBorderWidth(skinModel.getHeaderBorderWidth());
			skinEntity.setHeaderBorderColor(skinModel.getHeaderBorderColor());
			skinEntity.setHeaderFontFamily(skinModel.getHeaderFontFamily());
			skinEntity.setHeaderFontSize(skinModel.getHeaderFontSize());
			skinEntity.setHeaderFontStyle(skinModel.getHeaderFontStyle());
			skinEntity.setHeaderFontVariant(skinModel.getHeaderFontVariant());
			skinEntity.setHeaderFontWeight(skinModel.getHeaderFontWeight());
			skinEntity.setHeaderTextColor(skinModel.getHeaderTextColor());
			skinEntity.setHeaderTextDecoration(skinModel.getHeaderTextDecoration());
			skinEntity.setToolbarBackgroundColor(skinModel.getToolbarBackgroundColor());
			skinEntity.setToolbarBackgroundImage(skinModel.getToolbarBackgroundImage());
			skinEntity.setToolbarGradientColor(skinModel.getToolbarGradientColor());
			skinEntity.setToolbarBorderColor(skinModel.getToolbarBorderColor());
			skinEntity.setToolbarBorderStyle(skinModel.getToolbarBorderStyle());
			skinEntity.setToolbarBorderWidth(skinModel.getToolbarBorderWidth());
			skinEntity.setToolbarFontFamily(skinModel.getToolbarFontFamily());
			skinEntity.setToolbarFontSize(skinModel.getToolbarFontSize());
			skinEntity.setToolbarFontStyle(skinModel.getToolbarFontStyle());
			skinEntity.setToolbarFontVariant(skinModel.getToolbarFontVariant());
			skinEntity.setToolbarFontWeight(skinModel.getToolbarFontWeight());
			skinEntity.setToolbarTextColor(skinModel.getToolbarTextColor());
			skinEntity.setToolbarTextDecoration(skinModel.getToolbarTextDecoration());
			skinEntity.setTabBackgroundColor(skinModel.getTabBackgroundColor());
			skinEntity.setTabBackgroundImage(skinModel.getTabBackgroundImage());
			skinEntity.setTabGradientColor(skinModel.getTabGradientColor());
			skinEntity.setTabBorderColor(skinModel.getTabBorderColor());
			skinEntity.setTabCornerRadius(skinModel.getTabCornerRadius());
			skinEntity.setTabFontFamily(skinModel.getTabFontFamily());
			skinEntity.setTabFontSize(skinModel.getTabFontSize());
			skinEntity.setTabFontStyle(skinModel.getTabFontStyle());
			skinEntity.setTabFontWeight(skinModel.getTabFontWeight());
			skinEntity.setTabTextColor(skinModel.getTabTextColor());
			skinEntity.setTabTextDecoration(skinModel.getTabTextDecoration());
			skinEntity.setTabActiveBackgroundColor(skinModel.getTabActiveBackgroundColor());
			skinEntity.setTabActiveBackgroundImage(skinModel.getTabActiveBackgroundImage());
			skinEntity.setTabActiveGradientColor(skinModel.getTabActiveGradientColor());
			skinEntity.setTabActiveBorderColor(skinModel.getTabActiveBorderColor());
			skinEntity.setTabActiveFontFamily(skinModel.getTabActiveFontFamily());
			skinEntity.setTabActiveFontSize(skinModel.getTabActiveFontSize());
			skinEntity.setTabActiveFontStyle(skinModel.getTabActiveFontStyle());
			skinEntity.setTabActiveFontWeight(skinModel.getTabActiveFontWeight());
			skinEntity.setTabActiveTextColor(skinModel.getTabActiveTextColor());
			skinEntity.setTabActiveTextDecoration(skinModel.getTabActiveTextDecoration());
			skinEntity.setTabInactiveBackgroundColor(skinModel.getTabInactiveBackgroundColor());
			skinEntity.setTabInactiveBackgroundImage(skinModel.getTabInactiveBackgroundImage());
			skinEntity.setTabInactiveGradientColor(skinModel.getTabInactiveGradientColor());
			skinEntity.setTabInactiveBorderColor(skinModel.getTabInactiveBorderColor());
			skinEntity.setTabInactiveFontFamily(skinModel.getTabInactiveFontFamily());
			skinEntity.setTabInactiveFontSize(skinModel.getTabInactiveFontSize());
			skinEntity.setTabInactiveFontStyle(skinModel.getTabInactiveFontStyle());
			skinEntity.setTabInactiveFontWeight(skinModel.getTabInactiveFontWeight());
			skinEntity.setTabInactiveTextColor(skinModel.getTabInactiveTextColor());
			skinEntity.setTabInactiveTextDecoration(skinModel.getTabInactiveTextDecoration());
			skinEntity.setTabDisabledBackgroundColor(skinModel.getTabDisabledBackgroundColor());
			skinEntity.setTabDisabledBackgroundImage(skinModel.getTabDisabledBackgroundImage());
			skinEntity.setTabDisabledGradientColor(skinModel.getTabDisabledGradientColor());
			skinEntity.setTabDisabledBorderColor(skinModel.getTabDisabledBorderColor());
			skinEntity.setTabDisabledFontFamily(skinModel.getTabDisabledFontFamily());
			skinEntity.setTabDisabledFontSize(skinModel.getTabDisabledFontSize());
			skinEntity.setTabDisabledFontStyle(skinModel.getTabDisabledFontStyle());
			skinEntity.setTabDisabledFontWeight(skinModel.getTabDisabledFontWeight());
			skinEntity.setTabDisabledTextColor(skinModel.getTabDisabledTextColor());
			skinEntity.setTabDisabledTextDecoration(skinModel.getTabDisabledTextDecoration());
			skinEntity.setTableBackgroundColor(skinModel.getTableBackgroundColor());
			skinEntity.setTableBorderColor(skinModel.getTableBorderColor());
			skinEntity.setTableBorderWidth(skinModel.getTableBorderWidth());
			skinEntity.setTableCellBackgroundColor(skinModel.getTableCellBackgroundColor());
			skinEntity.setTableCellBackgroundImage(skinModel.getTableCellBackgroundImage());
			skinEntity.setTableCellGradientColor(skinModel.getTableCellGradientColor());
			skinEntity.setTableCellBorderColor(skinModel.getTableCellBorderColor());
			skinEntity.setTableCellFontFamily(skinModel.getTableCellFontFamily());
			skinEntity.setTableCellFontSize(skinModel.getTableCellFontSize());
			skinEntity.setTableCellFontStyle(skinModel.getTableCellFontStyle());
			skinEntity.setTableCellFontVariant(skinModel.getTableCellFontVariant());
			skinEntity.setTableCellFontWeight(skinModel.getTableCellFontWeight());
			skinEntity.setTableCellTextColor(skinModel.getTableCellTextColor());
			skinEntity.setTableCellTextDecoration(skinModel.getTableCellTextDecoration());
			skinEntity.setTableHeaderBackgroundColor(skinModel.getTableHeaderBackgroundColor());
			skinEntity.setTableHeaderBackgroundImage(skinModel.getTableHeaderBackgroundImage());
			skinEntity.setTableHeaderGradientColor(skinModel.getTableHeaderGradientColor());
			skinEntity.setTableHeaderBorderColor(skinModel.getTableHeaderBorderColor());
			skinEntity.setTableHeaderFontFamily(skinModel.getTableHeaderFontFamily());
			skinEntity.setTableHeaderFontSize(skinModel.getTableHeaderFontSize());
			skinEntity.setTableHeaderFontStyle(skinModel.getTableHeaderFontStyle());
			skinEntity.setTableHeaderFontVariant(skinModel.getTableHeaderFontVariant());
			skinEntity.setTableHeaderFontWeight(skinModel.getTableHeaderFontWeight());
			skinEntity.setTableHeaderTextColor(skinModel.getTableHeaderTextColor());
			skinEntity.setTableHeaderTextDecoration(skinModel.getTableHeaderTextDecoration());
			skinEntity.setTableFooterBackgroundColor(skinModel.getTableFooterBackgroundColor());
			skinEntity.setTableFooterBackgroundImage(skinModel.getTableFooterBackgroundImage());
			skinEntity.setTableFooterGradientColor(skinModel.getTableFooterGradientColor());
			skinEntity.setTableFooterBorderColor(skinModel.getTableFooterBorderColor());
			skinEntity.setTableFooterFontFamily(skinModel.getTableFooterFontFamily());
			skinEntity.setTableFooterFontSize(skinModel.getTableFooterFontSize());
			skinEntity.setTableFooterFontStyle(skinModel.getTableFooterFontStyle());
			skinEntity.setTableFooterFontVariant(skinModel.getTableFooterFontVariant());
			skinEntity.setTableFooterFontWeight(skinModel.getTableFooterFontWeight());
			skinEntity.setTableFooterTextColor(skinModel.getTableFooterTextColor());
			skinEntity.setTableFooterTextDecoration(skinModel.getTableFooterTextDecoration());
			skinEntity.setTableSubHeaderBackgroundColor(skinModel.getTableSubHeaderBackgroundColor());
			skinEntity.setTableSubFooterBackgroundColor(skinModel.getTableSubFooterBackgroundColor());
			skinEntity.setTooltipBackgroundColor(skinModel.getTooltipBackgroundColor());
			skinEntity.setTooltipBackgroundImage(skinModel.getTooltipBackgroundImage());
			skinEntity.setTooltipGradientColor(skinModel.getTooltipGradientColor());
			skinEntity.setTooltipBorderColor(skinModel.getTooltipBorderColor());
			skinEntity.setTooltipBorderStyle(skinModel.getTooltipBorderStyle());
			skinEntity.setTooltipBorderWidth(skinModel.getTooltipBorderWidth());
			skinEntity.setTooltipFontFamily(skinModel.getTooltipFontFamily());
			skinEntity.setTooltipFontSize(skinModel.getTooltipFontSize());
			skinEntity.setTooltipFontStyle(skinModel.getTooltipFontStyle());
			skinEntity.setTooltipFontVariant(skinModel.getTooltipFontVariant());
			skinEntity.setTooltipFontWeight(skinModel.getTooltipFontWeight());
			skinEntity.setTooltipTextColor(skinModel.getTooltipTextColor());
			skinEntity.setTooltipTextDecoration(skinModel.getTooltipTextDecoration());
			skinEntity.setHighlightBackgroundColor(skinModel.getHighlightBackgroundColor());
			skinEntity.setHighlightBackgroundImage(skinModel.getHighlightBackgroundImage());
			skinEntity.setHighlightBorderStyle(skinModel.getHighlightBorderStyle());
			skinEntity.setHighlightBorderWidth(skinModel.getHighlightBorderWidth());
			skinEntity.setHighlightBorderColor(skinModel.getHighlightBorderColor());
			skinEntity.setHighlightFontFamily(skinModel.getHighlightFontFamily());
			skinEntity.setHighlightFontSize(skinModel.getHighlightFontSize());
			skinEntity.setHighlightFontStyle(skinModel.getHighlightFontStyle());
			skinEntity.setHighlightFontWeight(skinModel.getHighlightFontWeight());
			skinEntity.setHighlightTextColor(skinModel.getHighlightTextColor());
			skinEntity.setHighlightTextDecoration(skinModel.getHighlightTextDecoration());
			skinEntity.setHighlightControlColor(skinModel.getHighlightControlColor());
			skinEntity.setFocusBackgroundColor(skinModel.getFocusBackgroundColor());
			skinEntity.setFocusBackgroundImage(skinModel.getFocusBackgroundImage());
			skinEntity.setFocusGradientColor(skinModel.getFocusGradientColor());
			skinEntity.setFocusBorderStyle(skinModel.getFocusBorderStyle());
			skinEntity.setFocusBorderWidth(skinModel.getFocusBorderWidth());
			skinEntity.setFocusBorderColor(skinModel.getFocusBorderColor());
			skinEntity.setFocusFontFamily(skinModel.getFocusFontFamily());
			skinEntity.setFocusFontSize(skinModel.getFocusFontSize());
			skinEntity.setFocusFontStyle(skinModel.getFocusFontStyle());
			skinEntity.setFocusFontWeight(skinModel.getFocusFontWeight());
			skinEntity.setFocusTextColor(skinModel.getFocusTextColor());
			skinEntity.setFocusTextDecoration(skinModel.getFocusTextDecoration());
			skinEntity.setFocusControlColor(skinModel.getFocusControlColor());
			skinEntity.setDisabledBackgroundColor(skinModel.getDisabledBackgroundColor());
			skinEntity.setDisabledBackgroundImage(skinModel.getDisabledBackgroundImage());
			skinEntity.setDisabledBorderStyle(skinModel.getDisabledBorderStyle());
			skinEntity.setDisabledBorderWidth(skinModel.getDisabledBorderWidth());
			skinEntity.setDisabledBorderColor(skinModel.getDisabledBorderColor());
			skinEntity.setDisabledFontFamily(skinModel.getDisabledFontFamily());
			skinEntity.setDisabledFontSize(skinModel.getDisabledFontSize());
			skinEntity.setDisabledFontStyle(skinModel.getDisabledFontStyle());
			skinEntity.setDisabledFontWeight(skinModel.getDisabledFontWeight());
			skinEntity.setDisabledTextColor(skinModel.getDisabledTextColor());
			skinEntity.setDisabledTextDecoration(skinModel.getDisabledTextDecoration());
			skinEntity.setDisabledControlColor(skinModel.getDisabledControlColor());
			skinEntity.setThemeBorderColor(skinModel.getThemeBorderColor());
			skinEntity.setThemeBackgroundColor(skinModel.getThemeBackgroundColor());
		}
	}
	
	public List<SkinEntity> toEntityList(Collection<Skin> skinModelList) {
		if (skinModelList == null)
			return null;
		List<SkinEntity> skinEntityList = new ArrayList<SkinEntity>();
		for (Skin skinModel : skinModelList) {
			SkinEntity skinEntity = toEntity(skinModel);
			skinEntityList.add(skinEntity);
		}
		return skinEntityList;
	}
	
}
