//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Elements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Elements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://nam/model}include"/>
 *           &lt;element ref="{http://nam/model}class"/>
 *           &lt;element ref="{http://nam/model}type"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Elements", namespace = "http://nam/model", propOrder = {
    "includesAndClazzsAndTypes"
})
@XmlRootElement(name = "elements", namespace = "http://nam/model")
public class Elements
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "include", namespace = "http://nam/model", type = Include.class),
        @XmlElement(name = "class", namespace = "http://nam/model", type = Class.class),
        @XmlElement(name = "type", namespace = "http://nam/model", type = Type.class)
    })
    protected List<Serializable> includesAndClazzsAndTypes;

    /**
     * Gets the value of the includesAndClazzsAndTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includesAndClazzsAndTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludesAndClazzsAndTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Include }
     * {@link Class }
     * {@link Type }
     * 
     * 
     */
    public List<Serializable> getIncludesAndClazzsAndTypes() {
        if (includesAndClazzsAndTypes == null) {
            includesAndClazzsAndTypes = new ArrayList<Serializable>();
        }
        return this.includesAndClazzsAndTypes;
    }

}
