//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import nam.ui.View;


/**
 * <p>Java class for Extensions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Extensions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://nam/model}information"/>
 *           &lt;element ref="{http://nam/model}messaging"/>
 *           &lt;element ref="{http://nam/model}persistence"/>
 *           &lt;element ref="{http://nam/model}view"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Extensions", namespace = "http://nam/model", propOrder = {
    "informationsAndMessagingsAndPersistences"
})
@XmlRootElement(name = "extensions", namespace = "http://nam/model")
public class Extensions
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "information", namespace = "http://nam/model", type = Information.class),
        @XmlElement(name = "messaging", namespace = "http://nam/model", type = Messaging.class),
        @XmlElement(name = "persistence", namespace = "http://nam/model", type = Persistence.class),
        @XmlElement(name = "view", namespace = "http://nam/model", type = View.class)
    })
    protected List<Serializable> informationsAndMessagingsAndPersistences;

    /**
     * Gets the value of the informationsAndMessagingsAndPersistences property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the informationsAndMessagingsAndPersistences property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformationsAndMessagingsAndPersistences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Information }
     * {@link Messaging }
     * {@link Persistence }
     * {@link View }
     * 
     * 
     */
    public List<Serializable> getInformationsAndMessagingsAndPersistences() {
        if (informationsAndMessagingsAndPersistences == null) {
            informationsAndMessagingsAndPersistences = new ArrayList<Serializable>();
        }
        return this.informationsAndMessagingsAndPersistences;
    }

}
