//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Grouping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Grouping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://nam/model}id"/>
 *           &lt;element ref="{http://nam/model}item"/>
 *           &lt;element ref="{http://nam/model}secret"/>
 *           &lt;element ref="{http://nam/model}listItem"/>
 *           &lt;element ref="{http://nam/model}setItem"/>
 *           &lt;element ref="{http://nam/model}mapItem"/>
 *         &lt;/choice>
 *         &lt;element name="fields" type="{http://nam/model}Field" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Grouping", namespace = "http://nam/model", propOrder = {
    "idsAndItemsAndSecrets",
    "fields"
})
@XmlRootElement(name = "grouping", namespace = "http://nam/model")
public class Grouping implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "id", namespace = "http://nam/model", type = Id.class),
        @XmlElement(name = "item", namespace = "http://nam/model", type = Item.class),
        @XmlElement(name = "secret", namespace = "http://nam/model", type = Secret.class),
        @XmlElement(name = "listItem", namespace = "http://nam/model", type = ListItem.class),
        @XmlElement(name = "setItem", namespace = "http://nam/model", type = SetItem.class),
        @XmlElement(name = "mapItem", namespace = "http://nam/model", type = MapItem.class)
    })
    protected List<Field> idsAndItemsAndSecrets;
    @XmlElement(namespace = "http://nam/model")
    protected List<Field> fields;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the idsAndItemsAndSecrets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idsAndItemsAndSecrets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdsAndItemsAndSecrets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Id }
     * {@link Item }
     * {@link Secret }
     * {@link ListItem }
     * {@link SetItem }
     * {@link MapItem }
     * 
     * 
     */
    public List<Field> getIdsAndItemsAndSecrets() {
        if (idsAndItemsAndSecrets == null) {
            idsAndItemsAndSecrets = new ArrayList<Field>();
        }
        return this.idsAndItemsAndSecrets;
    }

    /**
     * Gets the value of the fields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getFields() {
        if (fields == null) {
            fields = new ArrayList<Field>();
        }
        return this.fields;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
