//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModuleLevel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ModuleLevel">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="project_level"/>
 *     &lt;enumeration value="group_level"/>
 *     &lt;enumeration value="application_level"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ModuleLevel", namespace = "http://nam/model")
@XmlEnum
public enum ModuleLevel {

    @XmlEnumValue("project_level")
    PROJECT_LEVEL("project_level"),
    @XmlEnumValue("group_level")
    GROUP_LEVEL("group_level"),
    @XmlEnumValue("application_level")
    APPLICATION_LEVEL("application_level");
    private final String value;

    ModuleLevel(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ModuleLevel fromValue(String v) {
        for (ModuleLevel c: ModuleLevel.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
