//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://nam/model}project"/>
 *         &lt;element ref="{http://nam/model}services"/>
 *         &lt;element ref="{http://nam/model}information"/>
 *         &lt;element ref="{http://nam/model}persistence"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "projectsAndServicesAndInformations"
})
@XmlRootElement(name = "placeholders", namespace = "http://nam/model")
public class Placeholders
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "project", namespace = "http://nam/model", type = Project.class),
        @XmlElement(name = "services", namespace = "http://nam/model", type = Services.class),
        @XmlElement(name = "information", namespace = "http://nam/model", type = Information.class),
        @XmlElement(name = "persistence", namespace = "http://nam/model", type = Persistence.class)
    })
    protected List<Serializable> projectsAndServicesAndInformations;

    /**
     * Gets the value of the projectsAndServicesAndInformations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectsAndServicesAndInformations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectsAndServicesAndInformations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Project }
     * {@link Services }
     * {@link Information }
     * {@link Persistence }
     * 
     * 
     */
    public List<Serializable> getProjectsAndServicesAndInformations() {
        if (projectsAndServicesAndInformations == null) {
            projectsAndServicesAndInformations = new ArrayList<Serializable>();
        }
        return this.projectsAndServicesAndInformations;
    }

}
