//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleTypeName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoleTypeName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Manager"/>
 *     &lt;enumeration value="User"/>
 *     &lt;enumeration value="Host"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoleTypeName", namespace = "http://nam/model")
@XmlEnum
public enum RoleTypeName {

    @XmlEnumValue("Manager")
    MANAGER("Manager"),
    @XmlEnumValue("User")
    USER("User"),
    @XmlEnumValue("Host")
    HOST("Host");
    private final String value;

    RoleTypeName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoleTypeName fromValue(String v) {
        for (RoleTypeName c: RoleTypeName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
