//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchemaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SchemaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="sql"/>
 *     &lt;enumeration value="xsd"/>
 *     &lt;enumeration value="wsdl"/>
 *     &lt;enumeration value="bpmn"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SchemaType", namespace = "http://nam/model")
@XmlEnum
public enum SchemaType {

    @XmlEnumValue("sql")
    SQL("sql"),
    @XmlEnumValue("xsd")
    XSD("xsd"),
    @XmlEnumValue("wsdl")
    WSDL("wsdl"),
    @XmlEnumValue("bpmn")
    BPMN("bpmn");
    private final String value;

    SchemaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SchemaType fromValue(String v) {
        for (SchemaType c: SchemaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
