//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tier.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Tier">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="ui"/>
 *     &lt;enumeration value="client"/>
 *     &lt;enumeration value="service"/>
 *     &lt;enumeration value="messaging"/>
 *     &lt;enumeration value="persistence"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Tier", namespace = "http://nam/model")
@XmlEnum
public enum Tier {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("ui")
    UI("ui"),
    @XmlEnumValue("client")
    CLIENT("client"),
    @XmlEnumValue("service")
    SERVICE("service"),
    @XmlEnumValue("messaging")
    MESSAGING("messaging"),
    @XmlEnumValue("persistence")
    PERSISTENCE("persistence");
    private final String value;

    Tier(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Tier fromValue(String v) {
        for (Tier c: Tier.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
