//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionOutcome.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionOutcome">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="commit"/>
 *     &lt;enumeration value="markedAsRollback"/>
 *     &lt;enumeration value="rollback"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransactionOutcome", namespace = "http://nam/model")
@XmlEnum
public enum TransactionOutcome {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("commit")
    COMMIT("commit"),
    @XmlEnumValue("markedAsRollback")
    MARKED_AS_ROLLBACK("markedAsRollback"),
    @XmlEnumValue("rollback")
    ROLLBACK("rollback");
    private final String value;

    TransactionOutcome(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransactionOutcome fromValue(String v) {
        for (TransactionOutcome c: TransactionOutcome.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
