//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Transports complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transports">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://nam/model}rmi-transport"/>
 *           &lt;element ref="{http://nam/model}ejb-transport"/>
 *           &lt;element ref="{http://nam/model}http-transport"/>
 *           &lt;element ref="{http://nam/model}jms-transport"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transports", namespace = "http://nam/model", propOrder = {
    "rmiTransportsAndEjbTransportsAndHttpTransports"
})
@XmlRootElement(name = "transports", namespace = "http://nam/model")
public class Transports implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "rmi-transport", namespace = "http://nam/model", type = RmiTransport.class),
        @XmlElement(name = "ejb-transport", namespace = "http://nam/model", type = EjbTransport.class),
        @XmlElement(name = "http-transport", namespace = "http://nam/model", type = HttpTransport.class),
        @XmlElement(name = "jms-transport", namespace = "http://nam/model", type = JmsTransport.class)
    })
    protected List<Transport> rmiTransportsAndEjbTransportsAndHttpTransports;

    /**
     * Gets the value of the rmiTransportsAndEjbTransportsAndHttpTransports property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rmiTransportsAndEjbTransportsAndHttpTransports property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRmiTransportsAndEjbTransportsAndHttpTransports().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RmiTransport }
     * {@link EjbTransport }
     * {@link HttpTransport }
     * {@link JmsTransport }
     * 
     * 
     */
    public List<Transport> getRmiTransportsAndEjbTransportsAndHttpTransports() {
        if (rmiTransportsAndEjbTransportsAndHttpTransports == null) {
            rmiTransportsAndEjbTransportsAndHttpTransports = new ArrayList<Transport>();
        }
        return this.rmiTransportsAndEjbTransportsAndHttpTransports;
    }

}
