//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.11 at 12:10:41 PM PDT 
//


package nam.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionContext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="correlationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expiration" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="isolationLevel" type="{http://nam/model}TransactionIsolationLevel"/>
 *         &lt;element name="coordinationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="registrationService" type="{http://nam/model}Endpoint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionContext", namespace = "http://nam/model", propOrder = {
    "correlationId",
    "transactionId",
    "expiration",
    "isolationLevel",
    "coordinationType",
    "registrationService"
})
@XmlRootElement(name = "transactionContext", namespace = "http://nam/model")
public class TransactionContext
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://nam/model", required = true)
    protected String correlationId;
    @XmlElement(namespace = "http://nam/model", required = true)
    protected String transactionId;
    @XmlElement(namespace = "http://nam/model")
    protected long expiration;
    @XmlElement(namespace = "http://nam/model", required = true)
    protected TransactionIsolationLevel isolationLevel;
    @XmlElement(namespace = "http://nam/model", required = true)
    protected String coordinationType;
    @XmlElement(namespace = "http://nam/model", required = true)
    protected Endpoint registrationService;

    /**
     * Gets the value of the correlationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationId(String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the expiration property.
     * 
     */
    public long getExpiration() {
        return expiration;
    }

    /**
     * Sets the value of the expiration property.
     * 
     */
    public void setExpiration(long value) {
        this.expiration = value;
    }

    /**
     * Gets the value of the isolationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionIsolationLevel }
     *     
     */
    public TransactionIsolationLevel getIsolationLevel() {
        return isolationLevel;
    }

    /**
     * Sets the value of the isolationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionIsolationLevel }
     *     
     */
    public void setIsolationLevel(TransactionIsolationLevel value) {
        this.isolationLevel = value;
    }

    /**
     * Gets the value of the coordinationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordinationType() {
        return coordinationType;
    }

    /**
     * Sets the value of the coordinationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordinationType(String value) {
        this.coordinationType = value;
    }

    /**
     * Gets the value of the registrationService property.
     * 
     * @return
     *     possible object is
     *     {@link Endpoint }
     *     
     */
    public Endpoint getRegistrationService() {
        return registrationService;
    }

    /**
     * Sets the value of the registrationService property.
     * 
     * @param value
     *     allowed object is
     *     {@link Endpoint }
     *     
     */
    public void setRegistrationService(Endpoint value) {
        this.registrationService = value;
    }

}
