package template1.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Generated by Nam.
 *
 */
@XmlType(name = "TreeNodeLevel")
@XmlEnum
public enum TreeNodeLevel {

	SGIUSA,
	TEAM,
	ZONE,
	REGION,
	AREA,
	CHAPTER,
	DISTRICT,
	GROUP,
	UNIT;

	public TreeNodeLevel fromValue(String name) {
		return valueOf(name);
	}

	public String value() {
		return name();
	}

}